using Anglr.Parser;
using Anglr.Parser.Core;
using System;
using System.Collections.Generic;
using System.Diagnostics.SymbolStore;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AnglrLibrary
{
	public partial class CSharpGenerator : CSharpBaseGenerator
	{
		public static readonly string g_CsNameSpace = "$(namespace)";
		public static readonly string g_CsClassname = "$(classname)";
		public static readonly string g_CsTables = "$(tables)";
		public static readonly string g_CsActions = "$(actions)";
		public static readonly string g_CsCounters = "$(counters)";
		public static readonly string g_CSEventRegistration = "$(evnreg)";
		public static readonly string g_CSEventDeclaration = "$(evndef)";
        public static readonly string g_UsingDeclarations = "$(UsingDeclarations)";
        public static readonly string g_ScannerNamespace = "$(ScannerNamespace)";
        public static readonly string g_ScannerClassDef = "$(ScannerClassDef)";
        public static readonly string g_ScannerRegexGetters = "$(ScannerRegexGetters)";
        public static readonly string g_ScannerClassTextReader = "$(ScannerClassTextReader)";
		public static readonly string g_ScannerClassStringArray = "$(ScannerClassStringArray)";
		public static readonly string g_ScannerClassString = "$(ScannerClassString)";
		public static readonly string g_ScannerCodes = "$(ScannerCodes)";
        public static readonly string g_InitialScanner = "$(InitialScanner)";
        public static readonly string g_ScannerInitCode = "$(ScannerInitCode)";
        public static readonly string g_MatchScanner = "$(MatchScanner)";
        public static readonly string g_prodIds = "$(prodIds)";
        public static readonly string g_fragments = "$(fragments)";

        public static readonly string g_ScannerEvents = "$(ScannerEvents)";
        public static readonly string g_StartRule = "$(StartRule)";

		public static readonly string [] g_ParserTemplateCsSrc =
		{
            "using System;",
			"using System.Collections;",
			"using System.Collections.Generic;",
			"using System.Linq;",
			"using System.Text;",
			"using System.Threading.Tasks;",
			"using System.Runtime.InteropServices;",
			"using System.IO;",
			"$(ScannerNamespace)",
            "using Anglr.Parser.Core;",
            "using Anglr.Parser.SyntaxTree;",
            "using AnglrLogLibrary;",
            "#if ANGLR_DEBUGGER",
            "using AnglrDebuggerBridge;",
            "#endif",
            "",
			"namespace $(namespace)",
			"{",
			"","\tpublic class $(classname) : SyntaxTreeBuilder, ParserInterface",
			"\t{",
            "\t\tpublic IAnglrLogger AnglrLogger { get; private set; }",
            "\t\tpublic event StartParserDelegate StartParserEvent;",
            "\t\tpublic event SyntaxErrorDelegate SyntaxErrorEvent;",
			"\t\tpublic event ShiftStepDelegate ShiftStepEvent;",
			"\t\tpublic event ReduceStepDelegate ReduceStepEvent;",
			"\t\tpublic event SplitStepDelegate SplitStepEvent;",
			"\t\tpublic event LoopStepDelegate LoopStepEvent;",
            "\t\tpublic event JoinDelegate JoinEvent;",
            "\t\tpublic event FinalStepDelegate FinalStepEvent;",
            "\t\tpublic event StopParserDelegate StopParserEvent;",
            "",
            "\t\tpublic void StartParserReport (int stackNr, object [] info = null) => StartParserEvent?.Invoke (stackNr, info);",
            "\t\tpublic void SyntaxErrorReport (int stackNr, int state) => SyntaxErrorEvent?.Invoke (stackNr, state);",
            "\t\tpublic void ShiftStepReport (int stackNr, int state, int tokenValue, string tokenName, string tokenText, bool conflict) => ShiftStepEvent?.Invoke (stackNr, state, tokenValue, tokenName, tokenText, conflict);",
            "\t\tpublic void ReduceStepReport (int stackNr, int prodNr, int ruleNr, string ruleName, int prodLen, int fallingState, int bottomState, int risingState, SyntaxTreeBase currentValue, bool bottom) => ReduceStepEvent?.Invoke (stackNr, prodNr, ruleNr, ruleName, prodLen, fallingState, bottomState, risingState, currentValue, bottom);",
            "\t\tpublic void SplitStepReport (int stackNr, int state, bool begin) => SplitStepEvent?.Invoke (stackNr, state, begin);",
            "\t\tpublic void LoopStepReport (int stackNr, int state) => LoopStepEvent?.Invoke (stackNr, state);",
            "\t\tpublic void JoinReport (int stackNr, int joinNr) => JoinEvent?.Invoke (stackNr, joinNr);",
            "\t\tpublic void FinalStepReport (int stackNr) => FinalStepEvent?.Invoke (stackNr);",
            "\t\tpublic void StopParserReport () => StopParserEvent?.Invoke ();",
            "\t\tpublic string [] GetStackText (int stackNr) => stackSet.GetStackText (stackNr);",
            "",
            "\t\tpublic bool FragmentParser { get; set; } = false;",
            "\t\tpublic int ProductionID { get; set; } = 0;",
            "\t\tpublic int InitialState { get; set; } = 0;",
            "\t\tpublic int LastToken { get; set; } = 0;",
            "\t\tpublic string LastTokenName { get; set; } = \"\";",
            "#if ANGLR_DEBUGGER",
            "\t\tpublic AnglrDebuggerClientBridge AnglrDebugBridgeObj { get; private set; }",
            "#endif",
            "",
            "\t\tpublic $(classname) (string fragmentName = null, IAnglrLogger anglrLogger = null) : base ()",
			"\t\t{",
            "\t\t\tAnglrLogger = anglrLogger;",
            "\t\t\t(int id, int state, int token, string tokenName) fragmentInfo = AnglrFragments.GetFragmentInfo (fragmentName);",
            "\t\t\tif (fragmentInfo.id != 0)",
            "\t\t\t{",
            "\t\t\t\tFragmentParser = true;",
            "\t\t\t\tProductionID = fragmentInfo.id;",
            "\t\t\t\tInitialState = fragmentInfo.state;",
            "\t\t\t\tLastToken = fragmentInfo.token;",
            "\t\t\t\tLastTokenName = fragmentInfo.tokenName;",
            "\t\t\t}",
            "\t\t\ttoken = new ParserToken (0, 0, null);",
			"\t\t\tstackSet = new stackset (new cmpstackid ());",
			"\t\t\tparseList = new parselist ();",
 			"\t\t\tstackSet.Add (new ParserStack (this));",
			"\t\t}",
			"",
			"\t\tpublic void reset ()",
			"\t\t{",
			"\t\t\ttoken = new ParserToken (0, 0, null);",
			"\t\t\tstackSet = new stackset (new cmpstackid ());",
			"\t\t\tparseList = new parselist ();",
 			"\t\t\tstackSet.Add (new ParserStack (this));",
			"\t\t}",
			"",
			"\t\tpublic bool CheckTokenInStack (ParserStack parserStack, int token)",
			"\t\t{",
			"\t\t\tint stackDepth = parserStack.stackDepth;",
			"\t\t\twhile (stackDepth-- > 0)",
			"\t\t\t{",
            "\t\t\t\tif (!parserStack.CheckTokenInState (token, parserStack.stateStack[stackDepth]))",
			"\t\t\t\t\tcontinue;",
			"\t\t\t\treturn true;",
			"\t\t\t}",
			"\t\t\treturn false;",
			"\t\t}",
			"",
            "#if ANGLR_DEBUGGER",
            "\t\tprivate void CreateDebuggerConnection ()",
            "\t\t{",
            "\t\t\tthis.AnglrDebugBridgeObj = new AnglrDebuggerClientBridge (this);",
            "\t\t}",
            "\t\tprivate void DisposeDebuggerConnection ()",
            "\t\t{",
            "\t\t\tthis.AnglrDebugBridgeObj?.Dispose ();",
            "\t\t}",
            "#endif",
            "",
			"\t\tpublic int parse ($(ScannerClassDef) scanner)",
			"\t\t{",
			"\t\t\tint step = 0;",
			"\t\t\tint finalCount = 0;",
			"\t\t\tint syntaxCnt = 0;",
			"\t\t\tint tokenCnt = 0;",
			"\t\t\tint shiftCnt = 0;",
			"\t\t\tint reduceCnt = 0;",
			"\t\t\tint splitCnt = 0;",
			"\t\t\tint joinCnt = 0;",
			"\t\t\tbool eofCondition = false;",
			"\t\t\tbool errCondition = false;",
            "",
            "\t\t\ttry",
            "\t\t\t{",
            "#if ANGLR_DEBUGGER",
            "\t\t\tCreateDebuggerConnection ();",
            "#endif",
            "",
            "\t\t\tStartParserReport (ParserStack.g_stackCounter, scanner.Info);",
            "",
			"\t\t\twhile (true)",
			"\t\t\t{",
			"\t\t\t\t++step;",
            "\t\t\t\tAnglrLogger?.DebugRawLine (\"STEP   \" + step + \", \" + stackSet.Count);",
			"\t\t\t\tint tokenRequest = 0;",
			"\t\t\t\tint shiftRequest = 0;",
			"\t\t\t\tstacklist delStackList = new stacklist ();",
			"\t\t\t\tstacklist insStackList = new stacklist ();",
			"\t\t\t\tstacklist errStackList = new stacklist ();",
			"",
			"\t\t\t\tforeach (ParserStack set in stackSet)",
			"\t\t\t\t{",
			"\t\t\t\t\twhile (true)",
			"\t\t\t\t\t{",
			"\t\t\t\t\t\tswitch (set.Step (insStackList, delStackList))",
			"\t\t\t\t\t\t{",
			"\t\t\t\t\t\tcase StepOutcome.NoStep:",
            "\t\t\t\t\t\t\tAnglrLogger?.DebugRawLine (\"NOSTEP \" + set.stackCounter);",
			"\t\t\t\t\t\t\tdelStackList.Add (set);",
			"\t\t\t\t\t\t\t++syntaxCnt;",
			"\t\t\t\t\t\t\tbreak;",
			"\t\t\t\t\t\tcase StepOutcome.ResizeFailed:",
            "\t\t\t\t\t\t\tAnglrLogger?.DebugRawLine (\"RESIZE \" + set.stackCounter);",
			"\t\t\t\t\t\t\tdelStackList.Add (set);",
			"\t\t\t\t\t\t\t++syntaxCnt;",
			"\t\t\t\t\t\t\tbreak;",
			"\t\t\t\t\t\tcase StepOutcome.SyntaxError:",
            "\t\t\t\t\t\t\tAnglrLogger?.DebugRawLine (\"SYNTAX \" + set.stackCounter + \" '\" + set.tokenText + \"' (\" + set.tokenValue + \")\");",
			"\t\t\t\t\t\t\terrStackList.Add (set);",
			"\t\t\t\t\t\t\t++syntaxCnt;",
			"\t\t\t\t\t\t\tbreak;",
			"\t\t\t\t\t\tcase StepOutcome.LoopStep:",
            "\t\t\t\t\t\t\tAnglrLogger?.DebugRawLine (\"LOOP   \" + set.stackCounter);",
			"\t\t\t\t\t\t\tdelStackList.Add (set);",
			"\t\t\t\t\t\t\t++syntaxCnt;",
			"\t\t\t\t\t\t\tbreak;",
			"\t\t\t\t\t\tcase StepOutcome.TokenUnavailable:",
			"\t\t\t\t\t\t\t++tokenRequest;",
			"\t\t\t\t\t\t\t++tokenCnt;",
			"\t\t\t\t\t\t\tbreak;",
			"\t\t\t\t\t\tcase StepOutcome.ShiftStep:",
			"\t\t\t\t\t\t\t++shiftRequest;",
			"\t\t\t\t\t\t\t++shiftCnt;",
			"\t\t\t\t\t\t\tbreak;",
			"\t\t\t\t\t\tcase StepOutcome.ReduceStep:",
			"\t\t\t\t\t\t\t++reduceCnt;",
			"\t\t\t\t\t\t\tcontinue;",
			"\t\t\t\t\t\t\t//break;",
			"\t\t\t\t\t\tcase StepOutcome.SplitStep:",
			"\t\t\t\t\t\t\tdelStackList.Add (set);",
			"\t\t\t\t\t\t\t++splitCnt;",
			"\t\t\t\t\t\t\tbreak;",
			"\t\t\t\t\t\tcase StepOutcome.FinalStep:",
			"\t\t\t\t\t\t\t++finalCount;",
			"\t\t\t\t\t\t\tset.valueStack.Pop ();",
			"\t\t\t\t\t\t\tparseList.Add (set.valueStack.Peek());",
			"\t\t\t\t\t\t\tdelStackList.Add (set);",
			"\t\t\t\t\t\t\tbreak;",
			"\t\t\t\t\t\t}",
			"\t\t\t\t\t\tbreak;",
			"\t\t\t\t\t}",
			"\t\t\t\t}",
			"",
			"\t\t\t\tforeach (ParserStack set in delStackList)",
            "\t\t\t\t\tstackSet.Remove (set);",
            "",
			"\t\t\t\tforeach (ParserStack set in insStackList)",
			"\t\t\t\t\tstackSet.Add (set);",
			"",
			"\t\t\t\tint size;",
			"\t\t\t\tif ((size = stackSet.Count) > 1)",
			"\t\t\t\t{",
			"\t\t\t\t\tint count = 0;",
			"\t\t\t\t\tstackset smap = new stackset (new cmpstackinfo ());",
			"\t\t\t\t\tforeach (ParserStack set in stackSet)",
			"\t\t\t\t\t{",
			"\t\t\t\t\t\tif (!smap.Contains (set))",
			"\t\t\t\t\t\t\tsmap.Add (set);",
			"\t\t\t\t\t\telse",
			"\t\t\t\t\t\t{",
            "\t\t\t\t\t\t\tAnglrLogger?.DebugRawLine (\"JOIN   \" + set.stackCounter + \", \" + set.m_equivalent.stackCounter);",
            "\t\t\t\t\t\t\tset.Join (set.m_equivalent);",
            "\t\t\t\t\t\t\tJoinReport (set.stackCounter, set.m_equivalent.stackCounter);",
            "\t\t\t\t\t\t\terrStackList.Remove (set);",
			"\t\t\t\t\t\t\t++joinCnt;",
			"\t\t\t\t\t\t}",
			"\t\t\t\t\t}",
			"\t\t\t\t\tif (smap.Count < stackSet.Count)",
			"\t\t\t\t\t{",
			"\t\t\t\t\t\tstackSet.Clear ();",
			"\t\t\t\t\t\tforeach (ParserStack set in smap)",
			"\t\t\t\t\t\t\tstackSet.Add (set);",
			"\t\t\t\t\t}",
			"\t\t\t\t\tif ((size = stackSet.Count) < 2)",
			"\t\t\t\t\t\t++count;",
			"\t\t\t\t}",
			"\t\t\t\tif (size == 0)",
			"\t\t\t\t{",
			"\t\t\t\t\tif (errStackList.Count == 0)",
			"\t\t\t\t\t\tbreak;",
			"\t\t\t\t}",
			"\t\t\t\telse",
			"\t\t\t\t{",
			"\t\t\t\t\tif (errStackList.Count < size)",
			"\t\t\t\t\t{",
			"\t\t\t\t\t\tforeach (ParserStack set in errStackList)",
            "\t\t\t\t\t\t{",
            "\t\t\t\t\t\t\tSyntaxErrorReport (set.stackCounter, -1);",
            "\t\t\t\t\t\t\tstackSet.Remove (set);",
            "\t\t\t\t\t\t}",
            "\t\t\t\t\t\terrStackList.Clear ();",
            "\t\t\t\t\t}",
			"\t\t\t\t}",
			"\t\t\t\terrCondition = (errStackList.Count > 0) && (errStackList.Count >= size);",
			"\t\t\t\tforeach (ParserStack set in errStackList)",
			"\t\t\t\t\tset.sequenceNr = token.sequenceNr;",
			"\t\t\t\tbool getToken = false;",
			"\t\t\t\tforeach (ParserStack set in stackSet)",
			"\t\t\t\t{",
			"\t\t\t\t\tif (set.sequenceNr < token.sequenceNr)",
			"\t\t\t\t\t{",
			"\t\t\t\t\t\tgetToken = true;",
			"\t\t\t\t\t\tbreak;",
			"\t\t\t\t\t}",
			"\t\t\t\t}",
			"\t\t\t\tif (!getToken)",
			"\t\t\t\t{",
			"\t\t\t\t\tif (errCondition)",
			"\t\t\t\t\t{",
			"\t\t\t\t\t\tif (Raise_Error_Event (this.token.lineno, this.token.column - this.token.tokenText.Length, this.token.token, this.token.tokenText))",
			"\t\t\t\t\t\t\tbreak;",
			"\t\t\t\t\t\tif (eofCondition)",
			"\t\t\t\t\t\t\tbreak;",
			"\t\t\t\t\t}",
			"\t\t\t\t\tint token = scanner.scan ();",
			"\t\t\t\t\tint secondary = scanner.secondary;",
			"\t\t\t\t\tint lineno = scanner.lineno;",
			"\t\t\t\t\tint column = scanner.column;",
			"\t\t\t\t\tstring tokenText = scanner.text;",
            "\t\t\t\t\tif (token < 0)",
            "\t\t\t\t\t{",
            "\t\t\t\t\t\tif (LastToken > 0)",
            "\t\t\t\t\t\t{",
            "\t\t\t\t\t\t\ttoken = LastToken;",
            "\t\t\t\t\t\t\ttokenText = LastTokenName;",
            "\t\t\t\t\t\t}",
            "\t\t\t\t\t\tLastToken = 0;",
            "\t\t\t\t\t}",
            "\t\t\t\t\tthis.token.Load ((eofCondition = (token <= 0)) ? (int) TerminalCodes.token__eof_token : token, secondary, lineno, column, tokenText);",
            "\t\t\t\t\tAnglrLogger?.DebugRawLine (\"TOKEN  '\" + tokenText + \"' (\" + token + \")\");",
			"\t\t\t\t\tforeach (ParserStack set in stackSet)",
			"\t\t\t\t\t\tset.LoadToken ();",
			"\t\t\t\t\tif (secondary > 0)",
			"\t\t\t\t\t{",
			"\t\t\t\t\t\tstackset parserStacks = new stackset (new cmpstackid ());",
			"\t\t\t\t\t\tforeach (ParserStack set in stackSet)",
			"\t\t\t\t\t\t{",
			"\t\t\t\t\t\t\tParserStack pset;",
			"\t\t\t\t\t\t\tparserStacks.Add (pset = new ParserStack (set));",
            "\t\t\t\t\t\t\tSplitStepReport (set.stackCounter, pset.stackCounter, true);",
            "\t\t\t\t\t\t\tpset.LoadSecondary ();",
            "\t\t\t\t\t\t}",
			"\t\t\t\t\t\tforeach (ParserStack set in parserStacks)",
			"\t\t\t\t\t\t\tstackSet.Add (set);",
			"\t\t\t\t\t}",
			"\t\t\t\t}",
			"\t\t\t}",
            "\t\t\tStopParserReport ();",
			"\t\t\tif (finalCount > 0)",
            "\t\t\t\tAnglrLogger?.DebugRawLine (\"       OK\\n\" +",
			"\t\t\t\t\t\"         final =  \" + finalCount + '\\n' +",
			"\t\t\t\t\t\"         syntax = \" + syntaxCnt + '\\n' +",
			"\t\t\t\t\t\"         token =  \" + tokenCnt + '\\n' +",
			"\t\t\t\t\t\"         shift =  \" + shiftCnt + '\\n' +",
			"\t\t\t\t\t\"         reduce = \" + reduceCnt + '\\n' +",
			"\t\t\t\t\t\"         split =  \" + splitCnt + '\\n' +",
			"\t\t\t\t\t\"         join =   \" + joinCnt + '\\n' +",
			"\t\t\t\t\t\"         steps =  \" + step);",
			"\t\t\telse",
            "\t\t\t\tAnglrLogger?.DebugRawLine (\"       NOK\");",
			"\t\t\treturn (finalCount > 0) ? 0 : -1;",
            "",
            "\t\t\t}",
            "\t\t\tfinally",
            "\t\t\t{",
            "#if ANGLR_DEBUGGER",
            "\t\t\t\tDisposeDebuggerConnection ();",
            "#endif",
            "\t\t\t}",
            "\t\t}",
			"",
            "\t\tSyntaxTreeBase ParserInterface.Build (ParserStack stack, int reductionNr, int prodLen)",
			"\t\t{",
			"\t\t\tvalstack valueStack = stack.valueStack;",
			"\t\t\tSyntaxTreeBase currentValue = null;",
			"",
			"\t\t\tswitch (reductionNr)",
			"\t\t\t{",
			"$(actions)",
			"\t\t\t}",
			"\t\t\treturn currentValue;",
			"\t\t}",
            "",
            "\t\tvoid ReportClassCounters ()",
			"\t\t{",
			"$(counters)",
			"\t\t\tif (SyntaxTreeToken.g_counter != 0)",
            "\t\t\t\tAnglrLogger?.DebugRawLine (\"SyntaxTreeToken.g_counter = \" + SyntaxTreeToken.g_counter);",
			"\t\t}",
			"",
            "\t\tbool ParserInterface.checkLoopDetection () => loopDetection;",
			"\t\tbool ParserInterface.checkDebug () => debug;",
			"\t\tbool ParserInterface.checkCreateParseTree () => createParseTree;",
			"\t\tParserToken ParserInterface.getToken () => token;",
            "\t\tint ParserInterface.magicNumber () => g_magicNumber;",
            "\t\tint ParserInterface.minTerminalCode () => g_minTerminalCode;",
            "\t\tint [] ParserInterface.terminalCodes () => g_terminalCodes;",
            "\t\tstring [] ParserInterface.terminalNames () => g_terminalNames;",
            "\t\tint ParserInterface.minNonTerminalCode () => g_minNonTerminalCode;",
            "\t\tint [] ParserInterface.nonTerminalCodes () => g_nonTerminalCodes;",
            "\t\tstring [] ParserInterface.nonTerminalNames () => g_nonTerminalNames;",
            "\t\tint [] ParserInterface.glrcheck () => g_glrcheck;",
			"\t\tint [] ParserInterface.glrstate () => g_glrstate;",
			"\t\tint [] ParserInterface.glrcells () => g_glrcells;",
			"\t\tint [] ParserInterface.check () => g_check;",
			"\t\tint [] ParserInterface.state () => g_state;",
			"\t\tint [] ParserInterface.shiftDelta () => g_shiftDelta;",
			"\t\tint [] ParserInterface.gotoDelta () => g_gotoDelta;",
			"\t\tint [] ParserInterface.productionLengths () => g_productionLengths;",
			"\t\tint [] ParserInterface.productionRules () => g_productionRules;",
			"\t\tint [] ParserInterface.defaultGoto () => g_defaultGoto;",
			"\t\tint [] ParserInterface.rcheck () => g_rcheck;",
			"\t\tint [] ParserInterface.rstate () => g_rstate;",
            "\t\tint [] ParserInterface.reductions () => g_reductions;",
            "",
            "\t\tpublic static bool debug { get; set; } = false;",
            "\t\tpublic static bool createParseTree { get; set; } = false;",
            "\t\tpublic static bool loopDetection { get; set; } = false;",
            "",
			"\t\tprivate static bool g_debug = false;",
			"\t\tprivate static bool g_createParseTree = false;",
			"\t\tprivate static bool g_loopDetection = false;",
			"",
			"\t\tpublic ParserToken token { get; private set; }",
			"\t\tpublic stackset stackSet { get; private set; }",
			"\t\tpublic parselist parseList { get; private set; }",
			"$(tables)",
			"\t}",
            "",
            "\tpublic partial class SyntaxTreeWalker : Anglr.Parser.Walker.SyntaxTreeWalkerCore { }",
            "",
			"\tpublic enum ProductionID",
			"\t{",
			"\t\tInvalidProductionID = 0,",
            "$(prodIds)",
            "\t\tLastProductionID",
			"\t};",
            "",
            "\tpublic static class AnglrFragments",
            "\t{",
            "\t\tpublic static readonly (string, ProductionID, int, int, string) [] FragmentsInfo =",
            "\t\t{",
            "$(fragments)",
            "\t\t};",
            "",
            "\t\tpublic static Dictionary<string, (int, int, int, string)> _FragmentsInfoDictionary = FragmentsInfo.ToDictionary (x => x.Item1, x => ((int) x.Item2, x.Item3, x.Item4, x.Item5));",
            "",
            "\t\tpublic static (int, int, int, string) GetFragmentInfo (string fragmentName) =>",
            "\t\t\t_FragmentsInfoDictionary.TryGetValue (fragmentName ?? \"\", out var fragment) ?",
            "\t\t\tfragment :",
            "\t\t\t(0, -1, -1, \"\");",
            "\t}",
            "",
            "\tpublic class $(classname)_TEST : SyntaxTreeWalker",
			"\t{",
			"\t\tpublic $(classname)_TEST ()",
			"\t\t{",
			"$(evnreg)",
			"\t\t}",
			"$(evndef)",
			"\t}",
            "",
            "\tinternal class $(classname)Example",
            "\t{",
            "\t\tstatic void Main (string [] args)",
            "\t\t{",
            "\t\t\t// parse every source file named in command line",
            "\t\t\tforeach (string arg in args)",
            "\t\t\t{",
            "\t\t\t\t$(classname) parser = new $(classname) ();",
            "\t\t\t\t$(ScannerClassDef) lexer = new $(ScannerClassDef) (new StreamReader (arg));",
            "",
            "\t\t\t\t// register method reporting syntax errors",
            "\t\t\t\tparser.Error_Event += (int lineno, int column, int token, string tokenString) =>",
            "\t\t\t\t{",
            "\t\t\t\t\tConsole.Error.WriteLine ($\"Syntax error: file ({arg}), line ({lineno}), column ({column}), token ({token} - {tokenString}\");",
            "\t\t\t\t\treturn true;\t// continue parsing",
            "\t\t\t\t};",
            "",
            "$(ScannerEvents)",
            "",
            "\t\t\t\t// invoke parser",
            "\t\t\t\t$(classname).createParseTree = true;",
            "\t\t\t\tif (parser.parse (lexer) != 0)",
            "\t\t\t\t\tcontinue;\t// errors, skip current file",
            "",
            "\t\t\t\t// visit every node of every syntax tree generated for current source file",
            "\t\t\t\tforeach (var syntaxTree in parser.parseList)",
            "\t\t\t\t{",
            "\t\t\t\t\t$(classname)_TEST testWalker = new $(classname)_TEST ();",
            "\t\t\t\t\ttestWalker.Traverse (syntaxTree as $(StartRule));",
            "\t\t\t\t}",
            "\t\t\t}",
            "\t\t}",
			"\t}",
			"}",
		};

		public static readonly string [] g_ParserTemplateCsHdr =
		{
			"#pragma once",
			"#include \"Syntax\\SyntaxTreeBuilder.h\"",
			"",
			"#include <iostream>",
			"#include <set>",
			"#include <map>",
			"#include <list>",
			"#include <deque>",
			"using namespace std;",
			"",
			"class $(classname) : public SyntaxTreeBuilder",
			"{",
			"private:",
			"\ttypedef SyntaxTreeBase* valstack;",
			"",
			"\tclass ParserToken",
			"\t{",
			"\tpublic:",
			"\t\tParserToken (int token, int secondary, char* tokenText) : m_sequenceNr (0), m_token (token), m_secondary (secondary), m_lineno (-1), m_column (-1), m_tokenText (tokenText) {}",
			"\t\tvirtual ~ParserToken () {}",
			"\t\tinline int sequenceNr () { return m_sequenceNr; }",
			"\t\tinline int token () { return m_token; }",
			"\t\tinline int secondary () { return m_secondary; }",
			"\t\tinline int lineno () { return m_lineno; }",
			"\t\tinline int column () { return m_column; }",
			"\t\tinline char* tokenText () { return m_tokenText; }",
			"\t\tinline void Load (int token, int secondary, int lineno, int column, char* tokenText) { m_token = token, m_secondary = secondary; m_lineno = lineno; m_column = column; m_tokenText = tokenText; ++m_sequenceNr; if (g_debug) cout << \"TOKEN  '\" << tokenText << \"' (\" << token << \")\" << endl; }",
			"\tprivate:",
			"\t\tint m_sequenceNr;",
			"\t\tint m_token;",
			"\t\tint m_secondary;",
			"\t\tint m_lineno;",
			"\t\tint m_column;",
			"\t\tchar* m_tokenText;",
			"\t};",
			"",
			"\ttypedef ParserToken* sharedtoken;",
			"",
			"\ttypedef enum",
			"\t{",
			"\t\tNoStep,",
			"\t\tResizeFailed,",
			"\t\tSyntaxError,",
			"\t\tTokenUnavailable,",
			"\t\tShiftStep,",
			"\t\tReduceStep,",
			"\t\tSplitStep,",
			"\t\tLoopStep,",
			"\t\tFinalStep,",
			"\t}\tStepOutcome;",
			"",
			"\tstruct StateStack",
			"\t{",
			"\tpublic:",
			"\t\tint m_state;",
			"\t\tint m_ruleNr;",
			"\t\tint m_depth;",
			"\t};",
			"",
			"\tclass ParserStack",
			"\t{",
			"\tpublic:",
			"\t\ttypedef list < ParserStack* > stacklist;",
			"\t\tParserStack ($(classname)& p_$(classname));",
			"\t\tParserStack (ParserStack& p_ParserStack);",
			"\t\tvirtual ~ParserStack ();",
			"\t\tvoid allocateStackValue (valstack val);",
			"\t\tvoid releaseStackValue (valstack val);",
			"\t\tStepOutcome Step (stacklist& insStackList, stacklist& delStackList);",
			"\t\tvalstack Build (int reductionNr, int ruleNr);",
			"\t\tvoid Shift (int state);",
			"\t\tStepOutcome Reduce (int productionNr);",
			"\t\tinline sharedtoken token () { return m_token; }",
			"\t\tinline int sequenceNr () { return m_sequenceNr; }",
			"\t\tinline int stackSize () { return m_stackSize; }",
			"\t\tinline int stackDepth () { return m_stackDepth; }",
			"\t\tinline int currentState () { return m_currentState; }",
			"\t\tinline int stackCounter () { return m_stackCounter; }",
			"\t\tinline int* stateStack () { return m_stateStack; }",
			"\t\tinline valstack* valueStack () { return m_valueStack; }",
			"\t\tinline void loadToken () { m_tokenValue = m_token->token(); m_tokenText = m_token->tokenText(); }",
			"\t\tinline int tokenValue() { return m_tokenValue; }",
			"\t\tinline char* tokenText() { return m_tokenText; }",
			"\t\tint Join (ParserStack* stack);",
			"\tprivate:",
			"\t\tint Resize ();",
			"\t\tint ResizeLoop ();",
			"\t\tvoid SaveState ();",
			"\tprivate:",
			"\t\tstatic int g_stackCounter;",
			"\t\tbool m_loopDetection;",
			"\t\tint m_stackCounter;",
			"\t\t$(classname)& m_$(classname);",
			"\t\tvalstack* m_valueStack;",
			"\t\tvalstack* m_valueStackTop;",
			"\t\tint* m_stateStack;",
			"\t\tint* m_stateStackTop;",
			"\t\tint m_stackSize;",
			"\t\tint m_stackDepth;",
			"\t\tStateStack* m_loopStack;",
			"\t\tStateStack* m_loopStackTop;",
			"\t\tint m_loopStackSize;",
			"\t\tint m_loopStackDepth;",
			"\t\tint m_currentState;",
			"\t\tvalstack m_currentValue;",
			"\t\tsharedtoken m_token;",
			"\t\tint m_tokenValue;",
			"\t\tchar* m_tokenText;",
			"\t\tint m_sequenceNr;",
			"\t};",
			"",
			"\ttypedef pair < int, int > stackinfo;",
			"\tclass cmpstackinfo : public less < ParserStack* >",
			"\t{",
			"\tpublic:",
			"\t\tbool operator () (const first_argument_type _Left, const second_argument_type _Right) const",
			"\t\t{",
			"\t\t\tif (x.tokenValue < y.tokenValue)",
			"\t\t\t\treturn -1;",
			"\t\t\tif (y.tokenValue < x.tokenValue)",
			"\t\t\t\treturn 1;",
			"\t\t\tint lsize = _Left->stackDepth();",
			"\t\t\tint rsize = _Right->stackDepth();",
			"\t\t\tif (lsize < rsize)",
			"\t\t\t\treturn true;",
			"\t\t\tif (rsize < lsize)",
			"\t\t\t\treturn false;",
			"\t\t\tint* lstack = _Left->stateStack ();",
			"\t\t\tint* rstack = _Right->stateStack ();",
			"\t\t\twhile (lsize-- > 0)",
			"\t\t\t{",
			"\t\t\t\tif (lstack[lsize] < rstack[lsize])",
			"\t\t\t\t\treturn true;",
			"\t\t\t\tif (rstack[lsize] < lstack[lsize])",
			"\t\t\t\t\treturn false;",
			"\t\t\t}",
			"\t\t\treturn false;",
			"\t\t}",
			"\t};",
			"\ttypedef set < ParserStack*, cmpstackinfo > stackmap;",
			"\tclass cmpstackid : public less < ParserStack* >",
			"\t{",
			"\tpublic:",
			"\t\tbool operator () (const first_argument_type _Left, const second_argument_type _Right) const",
			"\t\t{",
			"\t\t\treturn _Left->stackCounter () < _Right->stackCounter ();",
			"\t\t}",
			"\t};",
			"\ttypedef set < ParserStack*, cmpstackid > stackset;",
			"\ttypedef deque < ParserStack* > stackque;",
			"\ttypedef ParserStack::stacklist stacklist;",
			"",
			"public:",
			"\ttypedef list < SyntaxTreeBase* > parselist;",
			"public:",
			"\t$(classname) ();",
			"\tvirtual ~$(classname) ();",
			"\tinline parselist& getParseList () { return m_parselist; }",
			"",
			"\tint parse (void* yyscanner);",
			"\tinline sharedtoken token () { return m_token; }",
			"\tstatic inline void debug (bool debug) { g_debug = debug; }",
			"\tstatic inline bool debug () { return g_debug; }",
			"\tstatic inline void createParseTree (bool createParseTree) { g_createParseTree = createParseTree; }",
			"\tstatic inline bool createParseTree () { return g_createParseTree; }",
			"\tstatic inline void loopDetection (bool loopDetection) { g_loopDetection = loopDetection; }",
			"\tstatic inline bool loopDetection () { return g_loopDetection; }",
			"\tvoid ReportClassCounters ();",
			"private:",
			"private:",
			"\tstatic bool g_debug;",
			"\tstatic bool g_createParseTree;",
			"\tstatic bool g_loopDetection;",
            "\tstatic int g_minTerminalCode;",
            "\tstatic int g_terminalCodes[];",
            "\tstatic string g_terminalNames[];",
            "\tstatic int g_minNonTerminalCode;",
            "\tstatic int g_nonTerminalCodes[];",
            "\tstatic string g_nonTerminalNames[];",
            "\tstatic int g_check[];",
			"\tstatic int g_state[];",
			"\tstatic int g_shiftDelta[];",
			"\tstatic int g_gotoDelta[];",
			"\tstatic int g_productionLengths[];",
			"\tstatic int g_productionRules[];",
			"\tstatic int g_defaultGoto[];",
			"\tstatic int g_reductions[];",
			"\tstatic int g_rcheck[];",
			"\tstatic int g_rstate[];",
			"\tstatic int g_glrcheck[];",
			"\tstatic int g_glrstate[];",
			"\tstatic int g_glrcells[];",
			"",
			"\tsharedtoken m_token;",
			"\tstackset m_stackSet;",
			"\tstackque m_stackQue;",
			"\tparselist m_parselist;",
			"};",
			"",
			"typedef $(classname)::parselist parselist;",
		};

		public static readonly string [] g_EventTestBodyCs =
		{
			"\t\t{",
			"\t\t\tbool status = true;",
			"\t\t\tswitch (reason)",
			"\t\t\t{",
			"\t\t\tcase SyntaxTreeCallbackReason.BuilderCallbackReason:",
			"\t\t\t\tbreak;",
			"\t\t\tcase SyntaxTreeCallbackReason.TraversalPrologueCallbackReason:",
			"\t\t\t\tbreak;",
			"\t\t\tcase SyntaxTreeCallbackReason.TraversalMidTermCallbackReason:",
			"\t\t\t\tbreak;",
			"\t\t\tcase SyntaxTreeCallbackReason.TraversalEpilogueCallbackReason:",
			"\t\t\t\tbreak;",
			"\t\t\t}",
			"\t\t\treturn status;",
			"\t\t}",
		};
    }

    public partial class AnglrParserStatesGenerator : AnglrParserStatesBaseGenerator
    {
        public static readonly string g_CsNameSpace = "$(namespace)";
        public static readonly string g_CsClassname = "$(classname)";
        public static readonly string g_CsTables = "$(tables)";
        public static readonly string g_CsActions = "$(actions)";
        public static readonly string g_CsCounters = "$(counters)";
        public static readonly string g_CSEventRegistration = "$(evnreg)";
        public static readonly string g_CSEventDeclaration = "$(evndef)";
        public static readonly string g_UsingDeclarations = "$(UsingDeclarations)";
        public static readonly string g_ScannerNamespace = "$(ScannerNamespace)";
        public static readonly string g_ScannerClassDef = "$(ScannerClassDef)";
        public static readonly string g_ScannerRegexGetters = "$(ScannerRegexGetters)";
        public static readonly string g_ScannerClassTextReader = "$(ScannerClassTextReader)";
        public static readonly string g_ScannerClassStringArray = "$(ScannerClassStringArray)";
        public static readonly string g_ScannerClassString = "$(ScannerClassString)";
        public static readonly string g_ScannerCodes = "$(ScannerCodes)";
        public static readonly string g_InitialScanner = "$(InitialScanner)";
        public static readonly string g_ScannerInitCode = "$(ScannerInitCode)";
        public static readonly string g_MatchScanner = "$(MatchScanner)";
        public static readonly string g_prodIds = "$(prodIds)";
        public static readonly string g_fragments = "$(fragments)";

        public static readonly string [] g_ParserTemplateCsSrc =
        {
            "using System;",
            "using System.Collections;",
            "using System.Collections.Generic;",
            "using System.Linq;",
            "using System.Text;",
            "using System.Threading.Tasks;",
            "using System.Runtime.InteropServices;",
            "using System.IO;",
            "$(ScannerNamespace)",
            "using Anglr.Parser.Core;",
            "using Anglr.Parser.SyntaxTree;",
            "#if ANGLR_DEBUGGER",
            "using AnglrDebuggerBridge;",
            "#endif",
            "",
            "namespace $(namespace)",
            "{",
            "","\tpublic class $(classname) : SyntaxTreeBuilder, ParserInterface",
            "\t{",
            "\t\tpublic IAnglrLogger AnglrLogger { get; private set; }",
            "\t\tpublic event StartParserDelegate StartParserEvent;",
            "\t\tpublic event SyntaxErrorDelegate SyntaxErrorEvent;",
            "\t\tpublic event ShiftStepDelegate ShiftStepEvent;",
            "\t\tpublic event ReduceStepDelegate ReduceStepEvent;",
            "\t\tpublic event SplitStepDelegate SplitStepEvent;",
            "\t\tpublic event LoopStepDelegate LoopStepEvent;",
            "\t\tpublic event JoinDelegate JoinEvent;",
            "\t\tpublic event FinalStepDelegate FinalStepEvent;",
            "\t\tpublic event StopParserDelegate StopParserEvent;",
            "",
            "\t\tpublic void StartParserReport (int stackNr) => StartParserEvent?.Invoke (stackNr);",
            "\t\tpublic void SyntaxErrorReport (int stackNr, int state) => SyntaxErrorEvent?.Invoke (stackNr, state);",
            "\t\tpublic void ShiftStepReport (int stackNr, int state, int tokenValue, string tokenName, string tokenText, bool conflict) => ShiftStepEvent?.Invoke (stackNr, state, tokenValue, tokenName, tokenText, conflict);",
            "\t\tpublic void ReduceStepReport (int stackNr, int prodNr, int ruleNr, string ruleName, int prodLen, int fallingState, int bottomState, int risingState, SyntaxTreeBase currentValue, bool bottom) => ReduceStepEvent?.Invoke (stackNr, prodNr, ruleNr, ruleName, prodLen, fallingState, bottomState, risingState, currentValue, bottom);",
            "\t\tpublic void SplitStepReport (int stackNr, int state, bool begin) => SplitStepEvent?.Invoke (stackNr, state, begin);",
            "\t\tpublic void LoopStepReport (int stackNr, int state) => LoopStepEvent?.Invoke (stackNr, state);",
            "\t\tpublic void JoinReport (int stackNr, int joinNr) => JoinEvent?.Invoke (stackNr, joinNr);",
            "\t\tpublic void FinalStepReport (int stackNr) => FinalStepEvent?.Invoke (stackNr);",
            "\t\tpublic void StopParserReport () => StopParserEvent?.Invoke ();",
            "\t\tpublic string [] GetStackText (int stackNr) => stackSet.GetStackText (stackNr);",
            "",
            "\t\tpublic $(classname) (string fragmentName = null, IAnglrLogger anglrLogger = null) : base ()",
            "\t\t{",
            "\t\t\tAnglrLogger = anglrLogger;",
            "\t\t\ttoken = new ParserToken (0, 0, null);",
            "\t\t\tstackSet = new stackset (new cmpstackid ());",
            "\t\t\tparseList = new parselist ();",
             "\t\t\tstackSet.Add (new ParserStack (this));",
            "\t\t}",
            "",
            "\t\tpublic void reset ()",
            "\t\t{",
            "\t\t\ttoken = new ParserToken (0, 0, null);",
            "\t\t\tstackSet = new stackset (new cmpstackid ());",
            "\t\t\tparseList = new parselist ();",
             "\t\t\tstackSet.Add (new ParserStack (this));",
            "\t\t}",
            "",
            "\t\tpublic bool CheckTokenInStack (ParserStack parserStack, int token)",
            "\t\t{",
            "\t\t\tint stackDepth = parserStack.stackDepth;",
            "\t\t\twhile (stackDepth-- > 0)",
            "\t\t\t{",
            "\t\t\t\tif (!parserStack.CheckTokenInState (token, parserStack.stateStack[stackDepth]))",
            "\t\t\t\t\tcontinue;",
            "\t\t\t\treturn true;",
            "\t\t\t}",
            "\t\t\treturn false;",
            "\t\t}",
            "",
            "\t\tpublic int parse ($(ScannerClassDef) scanner)",
            "\t\t{",
            "\t\t\tint step = 0;",
            "\t\t\tint finalCount = 0;",
            "\t\t\tint syntaxCnt = 0;",
            "\t\t\tint tokenCnt = 0;",
            "\t\t\tint shiftCnt = 0;",
            "\t\t\tint reduceCnt = 0;",
            "\t\t\tint splitCnt = 0;",
            "\t\t\tint joinCnt = 0;",
            "\t\t\tbool eofCondition = false;",
            "\t\t\tbool errCondition = false;",
            "",
            "\t\t\twhile (true)",
            "\t\t\t{",
            "\t\t\t\t++step;",
            "\t\t\t\tAnglrLogger?.DebugRawLine (\"STEP   \" + step + \", \" + stackSet.Count);",
            "\t\t\t\tint tokenRequest = 0;",
            "\t\t\t\tint shiftRequest = 0;",
            "\t\t\t\tstacklist delStackList = new stacklist ();",
            "\t\t\t\tstacklist insStackList = new stacklist ();",
            "\t\t\t\tstacklist errStackList = new stacklist ();",
            "",
            "\t\t\t\tforeach (ParserStack set in stackSet)",
            "\t\t\t\t{",
            "\t\t\t\t\twhile (true)",
            "\t\t\t\t\t{",
            "\t\t\t\t\t\tswitch (set.Step (insStackList, delStackList))",
            "\t\t\t\t\t\t{",
            "\t\t\t\t\t\tcase StepOutcome.NoStep:",
            "\t\t\t\t\t\t\tAnglrLogger?.DebugRawLine (\"NOSTEP \" + set.stackCounter);",
            "\t\t\t\t\t\t\tdelStackList.Add (set);",
            "\t\t\t\t\t\t\t++syntaxCnt;",
            "\t\t\t\t\t\t\tbreak;",
            "\t\t\t\t\t\tcase StepOutcome.ResizeFailed:",
            "\t\t\t\t\t\t\tAnglrLogger?.DebugRawLine (\"RESIZE \" + set.stackCounter);",
            "\t\t\t\t\t\t\tdelStackList.Add (set);",
            "\t\t\t\t\t\t\t++syntaxCnt;",
            "\t\t\t\t\t\t\tbreak;",
            "\t\t\t\t\t\tcase StepOutcome.SyntaxError:",
            "\t\t\t\t\t\t\tAnglrLogger?.DebugRawLine (\"SYNTAX \" + set.stackCounter + \" '\" + set.tokenText + \"' (\" + set.tokenValue + \")\");",
            "\t\t\t\t\t\t\terrStackList.Add (set);",
            "\t\t\t\t\t\t\t++syntaxCnt;",
            "\t\t\t\t\t\t\tbreak;",
            "\t\t\t\t\t\tcase StepOutcome.LoopStep:",
            "\t\t\t\t\t\t\tAnglrLogger?.DebugRawLine (\"LOOP   \" + set.stackCounter);",
            "\t\t\t\t\t\t\tdelStackList.Add (set);",
            "\t\t\t\t\t\t\t++syntaxCnt;",
            "\t\t\t\t\t\t\tbreak;",
            "\t\t\t\t\t\tcase StepOutcome.TokenUnavailable:",
            "\t\t\t\t\t\t\t++tokenRequest;",
            "\t\t\t\t\t\t\t++tokenCnt;",
            "\t\t\t\t\t\t\tbreak;",
            "\t\t\t\t\t\tcase StepOutcome.ShiftStep:",
            "\t\t\t\t\t\t\t++shiftRequest;",
            "\t\t\t\t\t\t\t++shiftCnt;",
            "\t\t\t\t\t\t\tbreak;",
            "\t\t\t\t\t\tcase StepOutcome.ReduceStep:",
            "\t\t\t\t\t\t\t++reduceCnt;",
            "\t\t\t\t\t\t\tcontinue;",
            "\t\t\t\t\t\t\t//break;",
            "\t\t\t\t\t\tcase StepOutcome.SplitStep:",
            "\t\t\t\t\t\t\tdelStackList.Add (set);",
            "\t\t\t\t\t\t\t++splitCnt;",
            "\t\t\t\t\t\t\tbreak;",
            "\t\t\t\t\t\tcase StepOutcome.FinalStep:",
            "\t\t\t\t\t\t\t++finalCount;",
            "\t\t\t\t\t\t\tset.valueStack.Pop ();",
            "\t\t\t\t\t\t\tparseList.Add (set.valueStack.Peek());",
            "\t\t\t\t\t\t\tdelStackList.Add (set);",
            "\t\t\t\t\t\t\tbreak;",
            "\t\t\t\t\t\t}",
            "\t\t\t\t\t\tbreak;",
            "\t\t\t\t\t}",
            "\t\t\t\t}",
            "",
            "\t\t\t\tforeach (ParserStack set in delStackList)",
            "\t\t\t\t\tstackSet.Remove (set);",
            "",
            "\t\t\t\tforeach (ParserStack set in insStackList)",
            "\t\t\t\t\tstackSet.Add (set);",
            "",
            "\t\t\t\tint size;",
            "\t\t\t\tif ((size = stackSet.Count) > 1)",
            "\t\t\t\t{",
            "\t\t\t\t\tint count = 0;",
            "\t\t\t\t\tstackset smap = new stackset (new cmpstackinfo ());",
            "\t\t\t\t\tforeach (ParserStack set in stackSet)",
            "\t\t\t\t\t{",
            "\t\t\t\t\t\tif (!smap.Contains (set))",
            "\t\t\t\t\t\t\tsmap.Add (set);",
            "\t\t\t\t\t\telse",
            "\t\t\t\t\t\t{",
            "\t\t\t\t\t\t\tAnglrLogger?.DebugRawLine (\"JOIN   \" + set.stackCounter + \", \" + set.m_equivalent.stackCounter);",
            "\t\t\t\t\t\t\tset.Join (set.m_equivalent);",
            "\t\t\t\t\t\t\tJoinReport (set.stackCounter, set.m_equivalent.stackCounter);",
            "\t\t\t\t\t\t\terrStackList.Remove (set);",
            "\t\t\t\t\t\t\t++joinCnt;",
            "\t\t\t\t\t\t}",
            "\t\t\t\t\t}",
            "\t\t\t\t\tif (smap.Count < stackSet.Count)",
            "\t\t\t\t\t{",
            "\t\t\t\t\t\tstackSet.Clear ();",
            "\t\t\t\t\t\tforeach (ParserStack set in smap)",
            "\t\t\t\t\t\t\tstackSet.Add (set);",
            "\t\t\t\t\t}",
            "\t\t\t\t\tif ((size = stackSet.Count) < 2)",
            "\t\t\t\t\t\t++count;",
            "\t\t\t\t}",
            "\t\t\t\tif (size == 0)",
            "\t\t\t\t{",
            "\t\t\t\t\tif (errStackList.Count == 0)",
            "\t\t\t\t\t\tbreak;",
            "\t\t\t\t}",
            "\t\t\t\telse",
            "\t\t\t\t{",
            "\t\t\t\t\tif (errStackList.Count < size)",
            "\t\t\t\t\t{",
            "\t\t\t\t\t\tforeach (ParserStack set in errStackList)",
            "\t\t\t\t\t\t{",
            "\t\t\t\t\t\t\tSyntaxErrorReport (set.stackCounter, -1);",
            "\t\t\t\t\t\t\tstackSet.Remove (set);",
            "\t\t\t\t\t\t}",
            "\t\t\t\t\t\terrStackList.Clear ();",
            "\t\t\t\t\t}",
            "\t\t\t\t}",
            "\t\t\t\terrCondition = (errStackList.Count > 0) && (errStackList.Count >= size);",
            "\t\t\t\tforeach (ParserStack set in errStackList)",
            "\t\t\t\t\tset.sequenceNr = token.sequenceNr;",
            "\t\t\t\tbool getToken = false;",
            "\t\t\t\tforeach (ParserStack set in stackSet)",
            "\t\t\t\t{",
            "\t\t\t\t\tif (set.sequenceNr < token.sequenceNr)",
            "\t\t\t\t\t{",
            "\t\t\t\t\t\tgetToken = true;",
            "\t\t\t\t\t\tbreak;",
            "\t\t\t\t\t}",
            "\t\t\t\t}",
            "\t\t\t\tif (!getToken)",
            "\t\t\t\t{",
            "\t\t\t\t\tif (errCondition)",
            "\t\t\t\t\t{",
            "\t\t\t\t\t\tif (Raise_Error_Event (this.token.lineno, this.token.column - this.token.tokenText.Length, this.token.token, this.token.tokenText))",
            "\t\t\t\t\t\t\tbreak;",
            "\t\t\t\t\t\tif (eofCondition)",
            "\t\t\t\t\t\t\tbreak;",
            "\t\t\t\t\t}",
            "\t\t\t\t\tint token = scanner.scan ();",
            "\t\t\t\t\tint secondary = scanner.secondary;",
            "\t\t\t\t\tint lineno = scanner.lineno;",
            "\t\t\t\t\tint column = scanner.column;",
            "\t\t\t\t\tstring tokenText = scanner.text;",
            "\t\t\t\t\tthis.token.Load ((eofCondition = (token <= 0)) ? (int) TerminalCodes.token__eof_token : token, secondary, lineno, column, tokenText);",
            "\t\t\t\t\tAnglrLogger?.DebugRawLine (\"TOKEN  '\" + tokenText + \"' (\" + token + \")\");",
            "\t\t\t\t\tforeach (ParserStack set in stackSet)",
            "\t\t\t\t\t\tset.LoadToken ();",
            "\t\t\t\t\tif (secondary > 0)",
            "\t\t\t\t\t{",
            "\t\t\t\t\t\tstackset parserStacks = new stackset (new cmpstackid ());",
            "\t\t\t\t\t\tforeach (ParserStack set in stackSet)",
            "\t\t\t\t\t\t{",
            "\t\t\t\t\t\t\tParserStack pset;",
            "\t\t\t\t\t\t\tparserStacks.Add (pset = new ParserStack (set));",
            "\t\t\t\t\t\t\tSplitStepReport (set.stackCounter, pset.stackCounter, true);",
            "\t\t\t\t\t\t\tpset.LoadSecondary ();",
            "\t\t\t\t\t\t}",
            "\t\t\t\t\t\tforeach (ParserStack set in parserStacks)",
            "\t\t\t\t\t\t\tstackSet.Add (set);",
            "\t\t\t\t\t}",
            "\t\t\t\t}",
            "\t\t\t}",
            "\t\t\tif (finalCount > 0)",
            "\t\t\t\tAnglrLogger?.DebugRawLine (\"       OK\\n\" +",
            "\t\t\t\t\t\"         final =  \" + finalCount + '\\n' +",
            "\t\t\t\t\t\"         syntax = \" + syntaxCnt + '\\n' +",
            "\t\t\t\t\t\"         token =  \" + tokenCnt + '\\n' +",
            "\t\t\t\t\t\"         shift =  \" + shiftCnt + '\\n' +",
            "\t\t\t\t\t\"         reduce = \" + reduceCnt + '\\n' +",
            "\t\t\t\t\t\"         split =  \" + splitCnt + '\\n' +",
            "\t\t\t\t\t\"         join =   \" + joinCnt + '\\n' +",
            "\t\t\t\t\t\"         steps =  \" + step);",
            "\t\t\telse",
            "\t\t\t\tAnglrLogger?.DebugRawLine (\"       NOK\");",
            "\t\t\treturn (finalCount > 0) ? 0 : -1;",
            "\t\t}",
            "",
            "\t\tSyntaxTreeBase ParserInterface.Build (ParserStack stack, int reductionNr, int prodLen)",
            "\t\t{",
            "\t\t\tvalstack valueStack = stack.valueStack;",
            "\t\t\tSyntaxTreeBase currentValue = null;",
            "",
            "\t\t\tswitch (reductionNr)",
            "\t\t\t{",
            "$(actions)",
            "\t\t\t}",
            "\t\t\treturn currentValue;",
            "\t\t}",
            "",
            "\t\tvoid ReportClassCounters ()",
            "\t\t{",
            "$(counters)",
            "\t\t\tif (SyntaxTreeToken.g_counter != 0)",
            "\t\t\t\tAnglrLogger?.DebugRawLine (\"SyntaxTreeToken.g_counter = \" + SyntaxTreeToken.g_counter);",
            "\t\t}",
            "",
            "\t\tbool ParserInterface.checkLoopDetection () => loopDetection;",
            "\t\tbool ParserInterface.checkDebug () => debug;",
            "\t\tbool ParserInterface.checkCreateParseTree () => createParseTree;",
            "\t\tParserToken ParserInterface.getToken () => token;",
            "\t\tint ParserInterface.magicNumber () => g_magicNumber;",
            "\t\tint ParserInterface.minTerminalCode () => g_minTerminalCode;",
            "\t\tint [] ParserInterface.terminalCodes () => g_terminalCodes;",
            "\t\tstring [] ParserInterface.terminalNames () => g_terminalNames;",
            "\t\tint ParserInterface.minNonTerminalCode () => g_minNonTerminalCode;",
            "\t\tint [] ParserInterface.nonTerminalCodes () => g_nonTerminalCodes;",
            "\t\tstring [] ParserInterface.nonTerminalNames () => g_nonTerminalNames;",
            "\t\tint [] ParserInterface.glrcheck () => g_glrcheck;",
            "\t\tint [] ParserInterface.glrstate () => g_glrstate;",
            "\t\tint [] ParserInterface.glrcells () => g_glrcells;",
            "\t\tint [] ParserInterface.check () => g_check;",
            "\t\tint [] ParserInterface.state () => g_state;",
            "\t\tint [] ParserInterface.shiftDelta () => g_shiftDelta;",
            "\t\tint [] ParserInterface.gotoDelta () => g_gotoDelta;",
            "\t\tint [] ParserInterface.productionLengths () => g_productionLengths;",
            "\t\tint [] ParserInterface.productionRules () => g_productionRules;",
            "\t\tint [] ParserInterface.defaultGoto () => g_defaultGoto;",
            "\t\tint [] ParserInterface.rcheck () => g_rcheck;",
            "\t\tint [] ParserInterface.rstate () => g_rstate;",
            "\t\tint [] ParserInterface.reductions () => g_reductions;",
            "",
            "\t\tpublic static bool debug { get; set; } = false;",
            "\t\tpublic static bool createParseTree { get; set; } = false;",
            "\t\tpublic static bool loopDetection { get; set; } = false;",
            "",
            "\t\tprivate static bool g_debug = false;",
            "\t\tprivate static bool g_createParseTree = false;",
            "\t\tprivate static bool g_loopDetection = false;",
            "",
            "\t\tpublic ParserToken token { get; private set; }",
            "\t\tpublic stackset stackSet { get; private set; }",
            "\t\tpublic parselist parseList { get; private set; }",
            "$(tables)",
            "\t}",
            "",
            "\tpublic partial class SyntaxTreeWalker : Anglr.Parser.Walker.SyntaxTreeWalkerCore { }",
            "",
            "\tpublic enum ProductionID",
            "\t{",
            "\t\tInvalidProductionID = 0,",
            "$(prodIds)",
            "\t\tLastProductionID",
            "\t};",
            "",
            "\tpublic static class AnglrFragments",
            "\t{",
            "\t\tpublic static readonly (string, ProductionID, int) [] FragmentsInfo =",
            "\t\t{",
            "$(fragments)",
            "\t\t};",
            "",
            "\t\tpublic static Dictionary<string, (ProductionID, int)> _FragmentsInfoDictionary = FragmentsInfo.ToDictionary (x => x.Item1, x => (x.Item2, x.Item3));",
            "",
            "\t\tpublic static (ProductionID, int) GetFragmentInfo (string fragmentName) =>",
            "\t\t\t_FragmentsInfoDictionary.ContainsKey (fragmentName) ?",
            "\t\t\t_FragmentsInfoDictionary [fragmentName] :",
            "\t\t\t(ProductionID.InvalidProductionID, -1);",
            "\t}",
            "",
            "\tpublic class $(classname)_TEST : SyntaxTreeWalker",
            "\t{",
            "\t\tpublic $(classname)_TEST ()",
            "\t\t{",
            "$(evnreg)",
            "\t\t}",
            "$(evndef)",
            "\t}",
            "}",
        };

        public static readonly string [] g_ParserTemplateCsHdr =
        {
            "#pragma once",
            "#include \"Syntax\\SyntaxTreeBuilder.h\"",
            "",
            "#include <iostream>",
            "#include <set>",
            "#include <map>",
            "#include <list>",
            "#include <deque>",
            "using namespace std;",
            "",
            "class $(classname) : public SyntaxTreeBuilder",
            "{",
            "private:",
            "\ttypedef SyntaxTreeBase* valstack;",
            "",
            "\tclass ParserToken",
            "\t{",
            "\tpublic:",
            "\t\tParserToken (int token, int secondary, char* tokenText) : m_sequenceNr (0), m_token (token), m_secondary (secondary), m_lineno (-1), m_column (-1), m_tokenText (tokenText) {}",
            "\t\tvirtual ~ParserToken () {}",
            "\t\tinline int sequenceNr () { return m_sequenceNr; }",
            "\t\tinline int token () { return m_token; }",
            "\t\tinline int secondary () { return m_secondary; }",
            "\t\tinline int lineno () { return m_lineno; }",
            "\t\tinline int column () { return m_column; }",
            "\t\tinline char* tokenText () { return m_tokenText; }",
            "\t\tinline void Load (int token, int secondary, int lineno, int column, char* tokenText) { m_token = token, m_secondary = secondary; m_lineno = lineno; m_column = column; m_tokenText = tokenText; ++m_sequenceNr; if (g_debug) cout << \"TOKEN  '\" << tokenText << \"' (\" << token << \")\" << endl; }",
            "\tprivate:",
            "\t\tint m_sequenceNr;",
            "\t\tint m_token;",
            "\t\tint m_secondary;",
            "\t\tint m_lineno;",
            "\t\tint m_column;",
            "\t\tchar* m_tokenText;",
            "\t};",
            "",
            "\ttypedef ParserToken* sharedtoken;",
            "",
            "\ttypedef enum",
            "\t{",
            "\t\tNoStep,",
            "\t\tResizeFailed,",
            "\t\tSyntaxError,",
            "\t\tTokenUnavailable,",
            "\t\tShiftStep,",
            "\t\tReduceStep,",
            "\t\tSplitStep,",
            "\t\tLoopStep,",
            "\t\tFinalStep,",
            "\t}\tStepOutcome;",
            "",
            "\tstruct StateStack",
            "\t{",
            "\tpublic:",
            "\t\tint m_state;",
            "\t\tint m_ruleNr;",
            "\t\tint m_depth;",
            "\t};",
            "",
            "\tclass ParserStack",
            "\t{",
            "\tpublic:",
            "\t\ttypedef list < ParserStack* > stacklist;",
            "\t\tParserStack ($(classname)& p_$(classname));",
            "\t\tParserStack (ParserStack& p_ParserStack);",
            "\t\tvirtual ~ParserStack ();",
            "\t\tvoid allocateStackValue (valstack val);",
            "\t\tvoid releaseStackValue (valstack val);",
            "\t\tStepOutcome Step (stacklist& insStackList, stacklist& delStackList);",
            "\t\tvalstack Build (int reductionNr, int ruleNr);",
            "\t\tvoid Shift (int state);",
            "\t\tStepOutcome Reduce (int productionNr);",
            "\t\tinline sharedtoken token () { return m_token; }",
            "\t\tinline int sequenceNr () { return m_sequenceNr; }",
            "\t\tinline int stackSize () { return m_stackSize; }",
            "\t\tinline int stackDepth () { return m_stackDepth; }",
            "\t\tinline int currentState () { return m_currentState; }",
            "\t\tinline int stackCounter () { return m_stackCounter; }",
            "\t\tinline int* stateStack () { return m_stateStack; }",
            "\t\tinline valstack* valueStack () { return m_valueStack; }",
            "\t\tinline void loadToken () { m_tokenValue = m_token->token(); m_tokenText = m_token->tokenText(); }",
            "\t\tinline int tokenValue() { return m_tokenValue; }",
            "\t\tinline char* tokenText() { return m_tokenText; }",
            "\t\tint Join (ParserStack* stack);",
            "\tprivate:",
            "\t\tint Resize ();",
            "\t\tint ResizeLoop ();",
            "\t\tvoid SaveState ();",
            "\tprivate:",
            "\t\tstatic int g_stackCounter;",
            "\t\tbool m_loopDetection;",
            "\t\tint m_stackCounter;",
            "\t\t$(classname)& m_$(classname);",
            "\t\tvalstack* m_valueStack;",
            "\t\tvalstack* m_valueStackTop;",
            "\t\tint* m_stateStack;",
            "\t\tint* m_stateStackTop;",
            "\t\tint m_stackSize;",
            "\t\tint m_stackDepth;",
            "\t\tStateStack* m_loopStack;",
            "\t\tStateStack* m_loopStackTop;",
            "\t\tint m_loopStackSize;",
            "\t\tint m_loopStackDepth;",
            "\t\tint m_currentState;",
            "\t\tvalstack m_currentValue;",
            "\t\tsharedtoken m_token;",
            "\t\tint m_tokenValue;",
            "\t\tchar* m_tokenText;",
            "\t\tint m_sequenceNr;",
            "\t};",
            "",
            "\ttypedef pair < int, int > stackinfo;",
            "\tclass cmpstackinfo : public less < ParserStack* >",
            "\t{",
            "\tpublic:",
            "\t\tbool operator () (const first_argument_type _Left, const second_argument_type _Right) const",
            "\t\t{",
            "\t\t\tif (x.tokenValue < y.tokenValue)",
            "\t\t\t\treturn -1;",
            "\t\t\tif (y.tokenValue < x.tokenValue)",
            "\t\t\t\treturn 1;",
            "\t\t\tint lsize = _Left->stackDepth();",
            "\t\t\tint rsize = _Right->stackDepth();",
            "\t\t\tif (lsize < rsize)",
            "\t\t\t\treturn true;",
            "\t\t\tif (rsize < lsize)",
            "\t\t\t\treturn false;",
            "\t\t\tint* lstack = _Left->stateStack ();",
            "\t\t\tint* rstack = _Right->stateStack ();",
            "\t\t\twhile (lsize-- > 0)",
            "\t\t\t{",
            "\t\t\t\tif (lstack[lsize] < rstack[lsize])",
            "\t\t\t\t\treturn true;",
            "\t\t\t\tif (rstack[lsize] < lstack[lsize])",
            "\t\t\t\t\treturn false;",
            "\t\t\t}",
            "\t\t\treturn false;",
            "\t\t}",
            "\t};",
            "\ttypedef set < ParserStack*, cmpstackinfo > stackmap;",
            "\tclass cmpstackid : public less < ParserStack* >",
            "\t{",
            "\tpublic:",
            "\t\tbool operator () (const first_argument_type _Left, const second_argument_type _Right) const",
            "\t\t{",
            "\t\t\treturn _Left->stackCounter () < _Right->stackCounter ();",
            "\t\t}",
            "\t};",
            "\ttypedef set < ParserStack*, cmpstackid > stackset;",
            "\ttypedef deque < ParserStack* > stackque;",
            "\ttypedef ParserStack::stacklist stacklist;",
            "",
            "public:",
            "\ttypedef list < SyntaxTreeBase* > parselist;",
            "public:",
            "\t$(classname) ();",
            "\tvirtual ~$(classname) ();",
            "\tinline parselist& getParseList () { return m_parselist; }",
            "",
            "\tint parse (void* yyscanner);",
            "\tinline sharedtoken token () { return m_token; }",
            "\tstatic inline void debug (bool debug) { g_debug = debug; }",
            "\tstatic inline bool debug () { return g_debug; }",
            "\tstatic inline void createParseTree (bool createParseTree) { g_createParseTree = createParseTree; }",
            "\tstatic inline bool createParseTree () { return g_createParseTree; }",
            "\tstatic inline void loopDetection (bool loopDetection) { g_loopDetection = loopDetection; }",
            "\tstatic inline bool loopDetection () { return g_loopDetection; }",
            "\tvoid ReportClassCounters ();",
            "private:",
            "private:",
            "\tstatic bool g_debug;",
            "\tstatic bool g_createParseTree;",
            "\tstatic bool g_loopDetection;",
            "\tstatic int g_minTerminalCode;",
            "\tstatic int g_terminalCodes[];",
            "\tstatic string g_terminalNames[];",
            "\tstatic int g_minNonTerminalCode;",
            "\tstatic int g_nonTerminalCodes[];",
            "\tstatic string g_nonTerminalNames[];",
            "\tstatic int g_check[];",
            "\tstatic int g_state[];",
            "\tstatic int g_shiftDelta[];",
            "\tstatic int g_gotoDelta[];",
            "\tstatic int g_productionLengths[];",
            "\tstatic int g_productionRules[];",
            "\tstatic int g_defaultGoto[];",
            "\tstatic int g_reductions[];",
            "\tstatic int g_rcheck[];",
            "\tstatic int g_rstate[];",
            "\tstatic int g_glrcheck[];",
            "\tstatic int g_glrstate[];",
            "\tstatic int g_glrcells[];",
            "",
            "\tsharedtoken m_token;",
            "\tstackset m_stackSet;",
            "\tstackque m_stackQue;",
            "\tparselist m_parselist;",
            "};",
            "",
            "typedef $(classname)::parselist parselist;",
        };

        public static readonly string [] g_EventTestBodyCs =
        {
            "\t\t{",
            "\t\t\tbool status = true;",
            "\t\t\tswitch (reason)",
            "\t\t\t{",
            "\t\t\tcase SyntaxTreeCallbackReason.BuilderCallbackReason:",
            "\t\t\t\tbreak;",
            "\t\t\tcase SyntaxTreeCallbackReason.TraversalPrologueCallbackReason:",
            "\t\t\t\tbreak;",
            "\t\t\tcase SyntaxTreeCallbackReason.TraversalMidTermCallbackReason:",
            "\t\t\t\tbreak;",
            "\t\t\tcase SyntaxTreeCallbackReason.TraversalEpilogueCallbackReason:",
            "\t\t\t\tbreak;",
            "\t\t\t}",
            "\t\t\treturn status;",
            "\t\t}",
        };
    }
}
