using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using Anglr.Parser;

namespace AnglrLibrary
{
	public partial class PDAGenerator : CSharpBaseGenerator
	{
		public static readonly string g_CppClassname = "$(classname)";
		public static readonly string g_CppTables = "$(tables)";
		public static readonly string g_CppActions = "$(actions)";

		public static readonly string g_RegexClassName = "$(RegexClassName)";
		public static readonly string g_ScannerNamespace = "$(ScannerNamespace)";
		public static readonly string g_ScannerClassRef = "$(ScannerClassRef)";
		public static readonly string g_ScannerClassDef = "$(ScannerClassDef)";
		public static readonly string g_ScannerClassTextReader = "$(ScannerClassTextReader)";
		public static readonly string g_ScannerClassStringArray = "$(ScannerClassStringArray)";
		public static readonly string g_ScannerClassString = "$(ScannerClassString)";
		public static readonly string g_ScannerCode = "$(ScannerCode)";
		public static readonly string g_ScannerAnonCode = "$(ScannerAnonCode)";
		public static readonly string g_ScannerRegexList = "$(ScannerRegexList)";
		public static readonly string g_ScannerCodes = "$(ScannerCodes)";
		public static readonly string g_ScannerTokenCodes = "$(ScannerTokenCodes)";
		public static readonly string g_InitialScanner = "$(InitialScanner)";
		public static readonly string g_MatchScanner = "$(MatchScanner)";

		static readonly string [] g_ParserTemplateCppSrc =
		{
			"#pragma once",
			"",
			"#include \"$(classname).h\"",
			"",
			"$(tables)",
			"",
			"bool $(classname)::g_debug = false;",
			"bool $(classname)::g_createParseTree = false;",
			"bool $(classname)::g_loopDetection = false;",
			"int $(classname)::ParserStack::g_stackCounter = 0;",
			"",
			"$(classname)::ParserStack::ParserStack ($(classname)& p_$(classname)) : m_$(classname) (p_$(classname))",
			"{",
			"\tm_loopDetection = $(classname)::g_loopDetection;",
			"\tm_stackCounter = ++g_stackCounter;",
			"\tm_valueStack = 0;",
			"\tm_valueStackTop = 0;",
			"\tm_stateStack = 0;",
			"\tm_stateStackTop = 0;",
			"\tm_stackSize = 0;",
			"\tm_stackDepth = 0;",
			"\tif (m_loopDetection)",
			"\t{",
			"\t\tm_loopStack = 0;",
			"\t\tm_loopStackTop = 0;",
			"\t\tm_loopStackSize = 0;",
			"\t\tm_loopStackDepth = 0;",
			"\t\tResizeLoop ();",
			"\t}",
			"\tResize ();",
			"\tm_currentState = 0;",
			"\tm_currentValue = 0;",
			"\tm_token = m_$(classname).token();",
			"\tm_sequenceNr = 0;",
			"\tm_tokenValue = 0;",
			"\tSaveState ();",
			"\tif (g_debug) cout << \"CREATE \" << m_stackCounter << endl;",
			"}",
			"",
			"$(classname)::ParserStack::ParserStack ($(classname)::ParserStack& parser) : m_$(classname) (parser.m_$(classname))",
			"{",
			"\tm_loopDetection = parser.m_loopDetection;",
			"\tm_stackCounter = ++g_stackCounter;",
			"\tm_stackSize = (((parser.m_stackDepth + 1) >> 6) + 1) << 6;",
			"\tm_stackDepth = parser.m_stackDepth;",
			"\tm_stateStack = new int [m_stackSize];",
			"\tm_stateStackTop = m_stateStack + m_stackDepth;",
			"\tm_valueStack = new valstack [m_stackSize];",
			"\tm_valueStackTop = m_valueStack + m_stackDepth;",
			"\tfor (int depth = 0; depth < m_stackDepth; ++depth)",
			"\t{",
			"\t\tm_stateStack[depth] = parser.m_stateStack[depth];",
			"\t\tallocateStackValue (m_valueStack[depth] = parser.m_valueStack[depth]);",
			"\t}",
			"\tm_currentState = m_stateStackTop [-1];",
			"\tm_currentValue = m_valueStackTop [-1];",
			"\tif (m_loopDetection)",
			"\t{",
			"\t\tm_loopStackSize = (((parser.m_loopStackDepth + 1) >> 6) + 1) << 6;",
			"\t\tm_loopStackDepth = parser.m_loopStackDepth;",
			"\t\tm_loopStack = new StateStack[m_loopStackSize];",
			"\t\tm_loopStackTop = m_loopStack + m_loopStackDepth;",
			"\t\tfor (int depth = 0; depth < m_loopStackDepth; ++depth)",
			"\t\t\tm_loopStack[depth] = parser.m_loopStack[depth];",
			"\t}",
			"\tm_token = parser.m_token;",
			"\tm_sequenceNr = parser.m_sequenceNr;",
			"\tm_tokenValue = parser.m_tokenValue;",
			"\tm_tokenText = parser.m_tokenText;",
			"\tif (g_debug) cout << \"CREATE \" << m_stackCounter << endl;",
			"}",
			"",
			"$(classname)::ParserStack::~ParserStack ()",
			"{",
			"\tfor (int depth = 0; depth < m_stackDepth; ++depth)",
			"\t\treleaseStackValue (m_valueStack[depth]);",
			"\tdelete [] m_valueStack;",
			"\tdelete [] m_stateStack;",
			"\tm_stackSize = 0;",
			"\tm_stackDepth = 0;",
			"\tif (m_loopDetection)",
			"\t{",
			"\t\tdelete [] m_loopStack;",
			"\t\tm_loopStackSize = 0;",
			"\t\tm_loopStackDepth = 0;",
			"\t}",
			"\tm_token = 0;",
			"\tif (g_debug) cout << \"DELETE \" << m_stackCounter << endl;",
			"}",
			"",
			"void $(classname)::ParserStack::allocateStackValue (valstack val)",
			"{",
			"\tif (val == 0)",
			"\t\treturn;",
			"\tval->incUsage();",
			"}",
			"",
			"void $(classname)::ParserStack::releaseStackValue (valstack val)",
			"{",
			"\tif (val == 0)",
			"\t\treturn;",
			"\tif (val->decUsage() <= 0)",
			"\t\tdelete val;",
			"}",
			"",
			"int $(classname)::ParserStack::Resize ()",
			"{",
			"\tif (m_stackDepth < m_stackSize)",
			"\t\treturn 0;",
			"",
			"\tint stackSize = m_stackSize + 64;",
			"\tint* stateStack = new int [stackSize];",
			"\tvalstack* valueStack = new valstack [stackSize];",
			"\tif ((stateStack == 0) || (valueStack == 0))",
			"\t\treturn -1;",
			"\tfor (int depth = 0; depth < m_stackDepth; ++depth)",
			"\t{",
			"\t\tstateStack[depth] = m_stateStack[depth];",
			"\t\tvalueStack[depth] = m_valueStack[depth];",
			"\t}",
			"\tdelete [] m_stateStack;",
			"\tdelete [] m_valueStack;",
			"\tm_stateStack = stateStack;",
			"\tm_stateStackTop = m_stateStack + m_stackDepth;",
			"\tm_valueStack = valueStack;",
			"\tm_valueStackTop = m_valueStack + m_stackDepth;",
			"\tm_stackSize = stackSize;",
			"\treturn 0;",
			"}",
			"",
			"int $(classname)::ParserStack::ResizeLoop ()",
			"{",
			"\tif (m_loopStackDepth < m_loopStackSize)",
			"\t\treturn 0;",
			"",
			"\tint loopStackSize = m_loopStackSize + 64;",
			"\tStateStack* loopStack = new StateStack [loopStackSize];",
			"\tif (loopStack == 0)",
			"\t\treturn -1;",
			"\tfor (int depth = 0; depth < m_loopStackDepth; ++depth)",
			"\t\tloopStack[depth] = m_loopStack[depth];",
			"\tdelete [] m_loopStack;",
			"\tm_loopStack = loopStack;",
			"\tm_loopStackTop = m_loopStack + m_loopStackDepth;",
			"\tm_loopStackSize = loopStackSize;",
			"\treturn 0;",
			"}",
			"",
			"void $(classname)::ParserStack::SaveState ()",
			"{",
			"\t*m_stateStackTop++ = m_currentState;",
			"\t*m_valueStackTop++ = m_currentValue;",
			"\t++m_stackDepth;",
			"}",
			"",
			"void $(classname)::ParserStack::Shift (int state)",
			"{",
			"\tif (g_debug) cout << \"SHIFT  \" << m_stackCounter << \" '\" << ((m_tokenText != 0) ? m_tokenText : \"\") << \"' (\" << m_tokenValue << \") : \" << m_currentState << \" --> \" << state << endl;",
			"\tm_currentState = state;",
			"\tif (g_createParseTree)",
			"\t{",
			"\t\tm_currentValue = new SyntaxTreeToken (m_tokenValue, m_token->lineno(), m_token->column(), m_tokenText);",
			"\t\tm_currentValue->incUsage ();",
			"\t}",
			"\tm_tokenValue = 0;",
			"\tm_tokenText = (char*) \"\";",
			"\tif (m_loopDetection)",
			"\t{",
			"\t\tm_loopStackTop = m_loopStack;",
			"\t\tm_loopStackDepth = 0;",
			"\t}",
			"\t++m_sequenceNr;",
			"\tSaveState ();",
			"}",
			"",
			"$(classname)::StepOutcome $(classname)::ParserStack::Reduce (int productionNr)",
			"{",
			"\tint ruleNr = g_productionRules[productionNr];",
			"\tint ruleLen = g_productionLengths[productionNr];",
			"\t\t\tif (ruleNr <= 0)",
			"\t\t\t{",
			"\t\t\t\tif (g_debug)",
			"\t\t\t\t\tcout << \"ACCEPT \" << stackCounter() << \" '\" << ((tokenText() != 0) ? tokenText() : (char*) \"\") << \"' (\" << tokenValue() << \") <\" << productionNr << \", \" << ruleNr << \", \" << ruleLen << \"> : \" << currentState();",
			"\t\t\t\treturn FinalStep;",
			"\t\t\t}",
			"\tif (g_debug) cout << \"REDUCE \" << m_stackCounter << \" '\" << ((m_tokenText != 0) ? m_tokenText : \"\") << \"' (\" << m_tokenValue << \") <\" << productionNr << \", \" << ruleNr << \", \" << ruleLen << \"> : \" << m_currentState << \" --> \";",
			"\tif (g_createParseTree)",
			"\t{",
			"\t\tif ((m_currentValue = Build (productionNr, ruleNr)) != 0)",
			"\t\t\tm_currentValue->incUsage ();",
			"\t}",
			"\tm_stateStackTop -= ruleLen;",
			"\tm_stackDepth -= ruleLen;",
			"\tint state = m_stateStackTop[-1];",
			"\tif (g_debug) cout << state;",
			"\tint idx = ruleNr + g_gotoDelta[state];",
			"\tif ((idx < 0) || (idx >= sizeof (g_check)/ sizeof(g_check[0])) || (g_check [idx] != ruleNr))",
			"\t\tm_currentState = g_defaultGoto[ruleNr];",
			"\telse",
			"\t\tm_currentState = g_state[idx];",
			"\tif (g_debug) cout << \" --> \" << m_currentState << endl;",
			"\tif (m_currentState < 0)",
			"\t\treturn FinalStep;",
			"",
			"\tbool loop = false;",
			"\tif (m_loopDetection)",
			"\t{",
			"\t\tfor (int depth = 0; depth < m_loopStackDepth; ++depth)",
			"\t\t{",
			"\t\t\tif ((m_loopStack[depth].m_state == state) && (m_loopStack[depth].m_ruleNr == productionNr) && (m_loopStack[depth].m_depth == m_stackDepth))",
			"\t\t\t{",
			"\t\t\t\tloop = true;",
			"\t\t\t\tbreak;",
			"\t\t\t}",
			"\t\t}",
			"\t\tResizeLoop ();",
			"\t\tm_loopStackTop->m_state = state;",
			"\t\tm_loopStackTop->m_ruleNr = productionNr;",
			"\t\tm_loopStackTop->m_depth = m_stackDepth;",
			"\t\t++m_loopStackTop;",
			"\t\t++m_loopStackDepth;",
			"\t}",
			"",
			"\tfor (int len = ruleLen; len > 0; --len)",
			"\t\treleaseStackValue (*--m_valueStackTop);",
			"\tSaveState ();",
			"\treturn loop ? LoopStep : ReduceStep;",
			"}",
			"",
			"$(classname)::StepOutcome $(classname)::ParserStack::Step (stacklist& insStackList, stacklist& delStackList)",
			"{",
			"\tint token;",
			"",
			"\tif (Resize () < 0)",
			"\t\treturn ResizeFailed;",
			"",
			"\tint stateDelta = g_shiftDelta [m_currentState];",
			"\tif (stateDelta < 0)",
			"\t{",
			"\t\tstateDelta = -stateDelta;",
			"\t\tif ((token = m_tokenValue) == 0)",
			"\t\t\treturn TokenUnavailable;",
			"",
			"\t\tint index = stateDelta + token;",
			"\t\tif ((index < 0) || (index >= sizeof (g_glrcheck) / sizeof (int)) || (g_glrcheck [index] != token))",
			"\t\t\treturn SyntaxError;",
			"",
			"\t\tint delta = g_glrstate[index];",
			"\t\tint size = g_glrcells[delta];",
			"\t\tint state = g_glrcells[delta + 1];",
			"",
			"\t\tif (size < 3)",
			"\t\t{",
			"\t\t\tShift (state);",
			"\t\t\treturn ShiftStep;",
			"\t\t}",
			"\t\telse if ((size == 3) && (state < 0))",
			"\t\t{",
			"\t\t\treturn Reduce (g_glrcells[delta + 2]);",
			"\t\t}",
			"",
			"\t\tif (g_debug) cout << \"SPLIT  \" << m_stackCounter << endl;",
			"\t\tif (state >= 0)",
			"\t\t{",
			"\t\t\tParserStack* stack = new ParserStack (*this); //m_$(classname).allocateStack (this);",
			"\t\t\tstack->Shift (state);",
			"\t\t\tinsStackList.push_back (stack);",
			"\t\t}",
			"\t\tfor (int count = 2; count < size; ++count)",
			"\t\t{",
			"\t\t\tParserStack* stack = new ParserStack (*this); //m_$(classname).allocateStack (this);",
			"\t\t\tswitch (stack->Reduce (g_glrcells[delta + count]))",
			"\t\t\t{",
			"\t\t\tcase ReduceStep:",
			"\t\t\t\tinsStackList.push_back (stack);",
			"\t\t\t\tbreak;",
			"\t\t\tcase LoopStep:",
			"\t\t\t\tdelStackList.push_back (stack);",
			"\t\t\t\tbreak;",
			"\t\t\tdefault:",
			"\t\t\t\tdelete stack;",
			"\t\t\t\tbreak;",
			"\t\t\t}",
			"\t\t}",
			"\t\tif (g_debug) cout << \"SPLIT  END\" << endl;",
			"\t\treturn SplitStep;",
			"\t}",
			"",
			"\tif (stateDelta != 0)",
			"\t{",
			"\t\tif ((token = m_tokenValue) == 0)",
			"\t\t\treturn TokenUnavailable;",
			"\t\tint index = stateDelta + token;",
			"\t\tif (!((index < 0) || (index >= sizeof (g_check) / sizeof (int)) || (g_check [index] != token)))",
			"\t\t{",
			"\t\t\tShift (g_state [index]);",
			"\t\t\treturn ShiftStep;",
			"\t\t}",
			"\t}",
			"",
			"\tint productionNr = g_reductions [m_currentState];",
			"\tif (productionNr != 0)",
			"\t{",
			"\t\tif (productionNr < 0)",
			"\t\t{",
			"\t\t\tif ((token = m_tokenValue) == 0)",
			"\t\t\t\treturn TokenUnavailable;",
			"\t\t\tint index = token - productionNr;",
			"\t\t\tif ((index < 0) || (index >= sizeof (g_rcheck) / sizeof (int)) || (g_rcheck[index] != token))",
			"\t\t\t\treturn SyntaxError;",
			"\t\t\tproductionNr = g_rstate[index];",
			"\t\t}",
			"\t\treturn Reduce (productionNr);",
			"\t}",
			"\telse",
			"\t\treturn SyntaxError;",
			"",
			"\treturn NoStep;",
			"}",
			"",
			"int $(classname)::ParserStack::Join (ParserStack* stack)",
			"{",
			"\tint cnt = 0;",
			"\tif (stack->stackDepth() != m_stackDepth)",
			"\t\treturn cnt;",
			"\tvalstack* valueStack = stack->valueStack();",
			"\tfor (int depth = 0; depth < m_stackDepth; ++depth)",
			"\t{",
			"\t\tSyntaxTreeBase* lvalue = m_valueStack[depth];",
			"\t\tSyntaxTreeBase* rvalue = valueStack[depth];",
			"\t\tif (lvalue != rvalue)",
			"\t\t{",
			"\t\t\tlvalue->join (rvalue);",
			"\t\t\t++cnt;",
			"\t\t}",
			"\t}",
			"\treturn cnt;",
			"}",
			"",
			"$(classname)::valstack $(classname)::ParserStack::Build (int reductionNr, int ruleNr)",
			"{",
			"\t$(classname)::valstack currentValue = 0;",
			"\tswitch (reductionNr)",
			"\t{",
			"$(actions)",
			"\t}",
			"\treturn currentValue;",
			"}",
			"",
			"$(classname)::$(classname) ()",
			"{",
			"\tm_token = sharedtoken (new ParserToken (0, 0, (char*)\"\"));",
			"\tm_stackSet.insert (new ParserStack (*this));",
			"}",
			"",
			"$(classname)::~$(classname) ()",
			"{",
			"\tfor (stackset::iterator it = m_stackSet.begin(); it != m_stackSet.end(); ++it)",
			"\t\tdelete *it;",
			"\tm_stackSet.clear();",
			"\tfor (stackque::iterator it = m_stackQue.begin(); it != m_stackQue.end(); ++it)",
			"\t\tdelete *it;",
			"\tm_stackQue.clear();",
			"}",
			"",
			"int $(classname)::parse ($(ScannerClassRef)* scanner)",
			"{",
			"\tint step = 0;",
			"\tint finalCount = 0;",
			"\tint syntaxCnt = 0;",
			"\tint tokenCnt = 0;",
			"\tint shiftCnt = 0;",
			"\tint reduceCnt = 0;",
			"\tint splitCnt = 0;",
			"\tint joinCnt = 0;",
			"\tbool eofCondition = false;",
			"\tbool errCondition = false;",
			"",
			"\twhile (true)",
			"\t{",
			"\t\t++step;",
			"\t\tif (g_debug) cout << endl << \"STEP   \" << step << \", \" << m_stackSet.size() << endl;",
			"\t\tint sequenceNr = -1;",
			"\t\tint tokenRequest = 0;",
			"\t\tint shiftRequest = 0;",
			"\t\tstacklist delStackList;",
			"\t\tstacklist insStackList;",
			"\t\tstacklist errStackList;",
			"\t\tfor (stackset::const_iterator sit = m_stackSet.begin(); sit != m_stackSet.end(); ++sit)",
			"\t\t{",
			"\t\t\twhile (true)",
			"\t\t\t{",
			"\t\t\t\tswitch ((*sit)->Step(insStackList, delStackList))",
			"\t\t\t\t{",
			"\t\t\t\tcase NoStep:",
			"\t\t\t\t\tif (g_debug) cout << \"NOSTEP \" << (*sit)->stackCounter() << endl;",
			"\t\t\t\t\tdelStackList.push_back (*sit);",
			"\t\t\t\t\t++syntaxCnt;",
			"\t\t\t\t\tbreak;",
			"\t\t\t\tcase ResizeFailed:",
			"\t\t\t\t\tif (g_debug) cout << \"RESIZE \" << (*sit)->stackCounter() << endl;",
			"\t\t\t\t\tdelStackList.push_back (*sit);",
			"\t\t\t\t\t++syntaxCnt;",
			"\t\t\t\t\tbreak;",
			"\t\t\t\tcase SyntaxError:",
			"\t\t\t\t\tif (g_debug) cout << \"SYNTAX \" << (*sit)->stackCounter() << \" '\" << (*sit)->tokenText() << \"' (\" << (*sit)->tokenValue() << \")\" << endl;",
			"\t\t\t\t\terrStackList.push_back (*sit);",
			"\t\t\t\t\t++syntaxCnt;",
			"\t\t\t\t\tbreak;",
			"\t\t\t\tcase LoopStep:",
			"\t\t\t\t\tif (g_debug) cout << \"LOOP   \" << (*sit)->stackCounter() << endl;",
			"\t\t\t\t\tdelStackList.push_back (*sit);",
			"\t\t\t\t\t++syntaxCnt;",
			"\t\t\t\t\tbreak;",
			"\t\t\t\tcase TokenUnavailable:",
			"\t\t\t\t\t++tokenRequest;",
			"\t\t\t\t\t++tokenCnt;",
			"\t\t\t\t\tbreak;",
			"\t\t\t\tcase ShiftStep:",
			"\t\t\t\t\t++shiftRequest;",
			"\t\t\t\t\t++shiftCnt;",
			"\t\t\t\t\tbreak;",
			"\t\t\t\tcase ReduceStep:",
			"\t\t\t\t\t++reduceCnt;",
			"\t\t\t\t\tcontinue;",
			"\t\t\t\t\tbreak;",
			"\t\t\t\tcase SplitStep:",
			"\t\t\t\t\tdelStackList.push_back (*sit);",
			"\t\t\t\t\t++splitCnt;",
			"\t\t\t\t\tbreak;",
			"\t\t\t\tcase FinalStep:",
			"\t\t\t\t\t++finalCount;",
			"\t\t\t\t\tm_parselist.push_back ((*sit)->valueStack()[1]);",
			"\t\t\t\t\tdelStackList.push_back (*sit);",
			"\t\t\t\t\tbreak;",
			"\t\t\t\t}",
			"\t\t\t\tbreak;",
			"\t\t\t}",
			"\t\t}",
			"\t\tfor (stacklist::iterator sit = delStackList.begin(); sit != delStackList.end(); ++sit)",
			"\t\t{",
			"\t\t\tm_stackSet.erase (*sit);",
			"\t\t\tdelete *sit; // releaseStack (*sit);",
			"\t\t}",
			"\t\tfor (stacklist::iterator sit = insStackList.begin(); sit != insStackList.end(); ++sit)",
			"\t\t{",
			"\t\t\tm_stackSet.insert (*sit);",
			"\t\t}",
			"",
			"\t\tsize_t size;",
			"\t\tif ((size = m_stackSet.size()) > 1)",
			"\t\t{",
			"\t\t\tint count = 0;",
			"\t\t\tstackmap smap;",
			"\t\t\tfor (stackset::const_iterator sit = m_stackSet.begin(); sit != m_stackSet.end(); ++sit)",
			"\t\t\t{",
			"\t\t\t\tint count = 0;",
			"\t\t\t\tstackmap::const_iterator it;",
			"\t\t\t\tif ((it = smap.find (*sit)) == smap.end())",
			"\t\t\t\t\tsmap.insert (*sit);",
			"\t\t\t\telse",
			"\t\t\t\t{",
			"\t\t\t\t\tif (g_debug) cout << \"JOIN   \" << (*it)->stackCounter() << \", \" << (*sit)->stackCounter() << endl;",
			"\t\t\t\t\t(*it)->Join (*sit);",
			"\t\t\t\t\terrStackList.remove (*sit);",
			"\t\t\t\t\tdelete *sit;",
			"\t\t\t\t\t++joinCnt;",
			"\t\t\t\t}",
			"\t\t\t}",
			"\t\t\tif (smap.size() < m_stackSet.size())",
			"\t\t\t{",
			"\t\t\t\tm_stackSet.clear();",
			"\t\t\t\tfor (stackmap::const_iterator it = smap.begin(); it != smap.end(); ++it)",
			"\t\t\t\t\tm_stackSet.insert (*it);",
			"\t\t\t}",
			"\t\t\tif (m_stackSet.size() < 2)",
			"\t\t\t\t++count;",
			"\t\t}",
			"\t\tif (size == 0)",
			"\t\t{",
			"\t\t\tif (errStackList.size () == 0)",
			"\t\t\t\tbreak;",
			"\t\t}",
			"\t\telse",
			"\t\t{",
			"\t\t\tif (errStackList.size () < size)",
			"\t\t\t{",
			"\t\t\t\tfor (stacklist::const_iterator sit = errStackList.begin (); sit != errStackList.end (); ++sit)",
			"\t\t\t\t{",
			"\t\t\t\t\tm_stackSet.erase (*sit);",
			"\t\t\t\t\tdelete* sit;",
			"\t\t\t\t}",
			"\t\t\t}",
			"\t\t}",
			"\t\terrCondition = (errStackList.size () > 0) && (errStackList.size () >= size);",
			"\t\tfor (stacklist::const_iterator sit = errStackList.begin (); sit != errStackList.end (); ++sit)",
			"\t\t\t(*sit)->sequenceNr (m_token->sequenceNr ());",
			"\t\tbool getToken = false;",
			"\t\tfor (stackset::const_iterator sit = m_stackSet.begin (); sit != m_stackSet.end (); ++sit)",
			"\t\t{",
			"\t\t\tif ((*sit)->sequenceNr () < m_token->sequenceNr ())",
			"\t\t\t{",
			"\t\t\t\tgetToken = true;",
			"\t\t\t\tbreak;",
			"\t\t\t}",
			"\t\t}",
			"\t\tif (!getToken)",
			"\t\t{",
			"\t\t\tif (errCondition)",
			"\t\t\t{",
			"\t\t\t\t//if (Raise_Error_Event (m_token->lineno (), m_token->column () - strlen (m_token->tokenText ()), m_token->token (), m_token->tokenText ()))",
			"\t\t\t\t//\tbreak;",
			"\t\t\t\tif (eofCondition)",
			"\t\t\t\t\tbreak;",
			"\t\t\t}",
			"\t\t\tint token = scanner->scan ();",
			"\t\t\tint secondary = scanner->secondary ();",
			"\t\t\tint lineno = scanner->lineno ();",
			"\t\t\tint column = scanner->column ();",
			"\t\t\tchar* tokenText = (char*) scanner->text ();",
			"\t\t\tm_token->Load ((eofCondition = (token <= 0)) ? -1 : token, secondary, lineno, column, tokenText);",
			"\t\t\tfor (stackset::const_iterator sit = m_stackSet.begin(); sit != m_stackSet.end(); ++sit)",
			"\t\t\t\t(*sit)->loadToken();",
			"\t\t\tif (secondary > 0)",
			"\t\t\t{",
			"\t\t\t\tstackset parserStacks;",
			"\t\t\t\tfor (stackset::const_iterator sit = m_stackSet.begin (); sit != m_stackSet.end (); ++sit)",
			"\t\t\t\t{",
			"\t\t\t\t\tParserStack* pset;",
			"\t\t\t\t\tparserStacks.insert (pset = new ParserStack (*(*sit)));",
			"\t\t\t\t\tpset->loadSecondary ();",
			"\t\t\t\t}",
			"\t\t\t\tfor (stackset::const_iterator sit = parserStacks.begin (); sit != parserStacks.end (); ++sit)",
			"\t\t\t\t\tm_stackSet.insert (*sit);",
			"\t\t\t}",
			"\t\t}",
			"\t}",
			"\tif ((finalCount > 0) || (m_stackSet.size () > 0))",
			"\t\tcout << \"       OK\" << endl",
			"\t\t<< \"         final =  \" << finalCount << endl",
			"\t\t<< \"         syntax = \" << syntaxCnt << endl",
			"\t\t<< \"         token =  \" << tokenCnt << endl",
			"\t\t<< \"         shift =  \" << shiftCnt << endl",
			"\t\t<< \"         reduce = \" << reduceCnt << endl",
			"\t\t<< \"         split =  \" << splitCnt << endl",
			"\t\t<< \"         join =   \" << joinCnt << endl",
			"\t\t<< \"         steps =  \" << step << endl;",
			"\telse",
			"\t\tcout << \"       NOK\" << endl;",
			"\treturn (finalCount > 0) ? 0 : -1;",
			"}"
		};

		public static readonly string [] g_ParserTemplateCppHdr =
		{
			"#pragma once",
			"#include \"SyntaxTreeBuilder.h\"",
			"#include \"$(ScannerClassRef).h\"",
			"",
			"#include <iostream>",
			"#include <set>",
			"#include <map>",
			"#include <list>",
			"#include <deque>",
			"using namespace std;",
			"",
			"class $(classname) : public SyntaxTreeBuilder",
			"{",
			"private:",
			"\ttypedef SyntaxTreeBase* valstack;",
			"",
			"\tclass ParserToken",
			"\t{",
			"\tpublic:",
			"\t\tParserToken (int token, int secondary, char* tokenText) : m_sequenceNr (0), m_token (token), m_secondary (secondary), m_lineno (-1), m_column (-1), m_tokenText (tokenText) {}",
			"\t\tvirtual ~ParserToken () {}",
			"\t\tinline int sequenceNr () { return m_sequenceNr; }",
			"\t\tinline int token () { return m_token; }",
			"\t\tinline int secondary () { return m_secondary; }",
			"\t\tinline int lineno () { return m_lineno; }",
			"\t\tinline int column () { return m_column; }",
			"\t\tinline char* tokenText () { return m_tokenText; }",
			"\t\tinline void Load (int token, int secondary, int lineno, int column, char* tokenText) { m_token = token, m_secondary = secondary; m_lineno = lineno; m_column = column; m_tokenText = tokenText; ++m_sequenceNr; if (g_debug) cout << \"TOKEN  '\" << tokenText << \"' (\" << token << \")\" << endl; }",
			"\tprivate:",
			"\t\tint m_sequenceNr;",
			"\t\tint m_token;",
			"\t\tint m_secondary;",
			"\t\tint m_lineno;",
			"\t\tint m_column;",
			"\t\tchar* m_tokenText;",
			"\t};",
			"",
			"\ttypedef ParserToken* sharedtoken;",
			"",
			"\ttypedef enum",
			"\t{",
			"\t\tNoStep,",
			"\t\tResizeFailed,",
			"\t\tSyntaxError,",
			"\t\tTokenUnavailable,",
			"\t\tShiftStep,",
			"\t\tReduceStep,",
			"\t\tSplitStep,",
			"\t\tLoopStep,",
			"\t\tFinalStep,",
			"\t}\tStepOutcome;",
			"",
			"\tstruct StateStack",
			"\t{",
			"\tpublic:",
			"\t\tint m_state;",
			"\t\tint m_ruleNr;",
			"\t\tint m_depth;",
			"\t};",
			"",
			"\tclass ParserStack",
			"\t{",
			"\tpublic:",
			"\t\ttypedef list < ParserStack* > stacklist;",
			"\t\tParserStack ($(classname)& p_$(classname));",
			"\t\tParserStack (ParserStack& p_ParserStack);",
			"\t\tvirtual ~ParserStack ();",
			"\t\tvoid allocateStackValue (valstack val);",
			"\t\tvoid releaseStackValue (valstack val);",
			"\t\tStepOutcome Step (stacklist& insStackList, stacklist& delStackList);",
			"\t\tvalstack Build (int reductionNr, int ruleNr);",
			"\t\tvoid Shift (int state);",
			"\t\tStepOutcome Reduce (int productionNr);",
			"\t\tinline sharedtoken token () { return m_token; }",
			"\t\tinline int sequenceNr () { return m_sequenceNr; }",
			"\t\tinline void sequenceNr (int sequenceNr) { m_sequenceNr = sequenceNr; }",
			"\t\tinline int stackSize () { return m_stackSize; }",
			"\t\tinline int stackDepth () { return m_stackDepth; }",
			"\t\tinline int currentState () { return m_currentState; }",
			"\t\tinline int stackCounter () { return m_stackCounter; }",
			"\t\tinline int* stateStack () { return m_stateStack; }",
			"\t\tinline valstack* valueStack () { return m_valueStack; }",
			"\t\tinline void loadToken () { m_tokenValue = m_token->token(); m_tokenText = m_token->tokenText (); }",
			"\t\tinline void loadSecondary () { m_tokenValue = m_token->secondary (); m_tokenText = m_token->tokenText (); }",
			"\t\tinline int tokenValue() { return m_tokenValue; }",
			"\t\tinline char* tokenText() { return m_tokenText; }",
			"\t\tint Join (ParserStack* stack);",
			"\tprivate:",
			"\t\tint Resize ();",
			"\t\tint ResizeLoop ();",
			"\t\tvoid SaveState ();",
			"\tprivate:",
			"\t\tstatic int g_stackCounter;",
			"\t\tbool m_loopDetection;",
			"\t\tint m_stackCounter;",
			"\t\t$(classname)& m_$(classname);",
			"\t\tvalstack* m_valueStack;",
			"\t\tvalstack* m_valueStackTop;",
			"\t\tint* m_stateStack;",
			"\t\tint* m_stateStackTop;",
			"\t\tint m_stackSize;",
			"\t\tint m_stackDepth;",
			"\t\tStateStack* m_loopStack;",
			"\t\tStateStack* m_loopStackTop;",
			"\t\tint m_loopStackSize;",
			"\t\tint m_loopStackDepth;",
			"\t\tint m_currentState;",
			"\t\tvalstack m_currentValue;",
			"\t\tsharedtoken m_token;",
			"\t\tint m_tokenValue;",
			"\t\tchar* m_tokenText;",
			"\t\tint m_sequenceNr;",
			"\t};",
			"",
			"\ttypedef pair < int, int > stackinfo;",
			"\tclass cmpstackinfo : public less < ParserStack* >",
			"\t{",
			"\tpublic:",
			"\t\tbool operator () (const first_argument_type _Left, const second_argument_type _Right) const",
			"\t\t{",
			"\t\t\tif (_Left->tokenValue() < _Right->tokenValue())",
			"\t\t\t\treturn false;",
			"\t\t\tif (_Right->tokenValue() < _Left->tokenValue())",
			"\t\t\t\treturn true;",
			"\t\t\tint lsize = _Left->stackDepth();",
			"\t\t\tint rsize = _Right->stackDepth();",
			"\t\t\tif (lsize < rsize)",
			"\t\t\t\treturn true;",
			"\t\t\tif (rsize < lsize)",
			"\t\t\t\treturn false;",
			"\t\t\tint* lstack = _Left->stateStack ();",
			"\t\t\tint* rstack = _Right->stateStack ();",
			"\t\t\twhile (lsize-- > 0)",
			"\t\t\t{",
			"\t\t\t\tif (lstack[lsize] < rstack[lsize])",
			"\t\t\t\t\treturn true;",
			"\t\t\t\tif (rstack[lsize] < lstack[lsize])",
			"\t\t\t\t\treturn false;",
			"\t\t\t}",
			"\t\t\treturn false;",
			"\t\t}",
			"\t};",
			"\ttypedef set < ParserStack*, cmpstackinfo > stackmap;",
			"\tclass cmpstackid : public less < ParserStack* >",
			"\t{",
			"\tpublic:",
			"\t\tbool operator () (const first_argument_type _Left, const second_argument_type _Right) const",
			"\t\t{",
			"\t\t\treturn _Left->stackCounter () < _Right->stackCounter ();",
			"\t\t}",
			"\t};",
			"\ttypedef set < ParserStack*, cmpstackid > stackset;",
			"\ttypedef deque < ParserStack* > stackque;",
			"\ttypedef ParserStack::stacklist stacklist;",
			"",
			"public:",
			"\ttypedef list < SyntaxTreeBase* > parselist;",
			"public:",
			"\t$(classname) ();",
			"\tvirtual ~$(classname) ();",
			"\tinline parselist& getParseList () { return m_parselist; }",
			"",
			"\tint parse ($(ScannerClassRef)* scanner);",
			"\tinline sharedtoken token () { return m_token; }",
			"\tstatic inline void debug (bool debug) { g_debug = debug; }",
			"\tstatic inline bool debug () { return g_debug; }",
			"\tstatic inline void createParseTree (bool createParseTree) { g_createParseTree = createParseTree; }",
			"\tstatic inline bool createParseTree () { return g_createParseTree; }",
			"\tstatic inline void loopDetection (bool loopDetection) { g_loopDetection = loopDetection; }",
			"\tstatic inline bool loopDetection () { return g_loopDetection; }",
			"\tvoid ReportClassCounters ();",
			"private:",
			"private:",
			"\tstatic bool g_debug;",
			"\tstatic bool g_createParseTree;",
			"\tstatic bool g_loopDetection;",
			"\tstatic int g_terminalCodes[];",
			"\tstatic int g_nonTerminalCodes[];",
			"\tstatic int g_check[];",
			"\tstatic int g_state[];",
			"\tstatic int g_shiftDelta[];",
			"\tstatic int g_gotoDelta[];",
			"\tstatic int g_productionLengths[];",
			"\tstatic int g_productionRules[];",
			"\tstatic int g_defaultGoto[];",
			"\tstatic int g_reductions[];",
			"\tstatic int g_rcheck[];",
			"\tstatic int g_rstate[];",
			"\tstatic int g_glrcheck[];",
			"\tstatic int g_glrstate[];",
			"\tstatic int g_glrcells[];",
			"",
			"\tsharedtoken m_token;",
			"\tstackset m_stackSet;",
			"\tstackque m_stackQue;",
			"\tparselist m_parselist;",
			"};",
			"",
			"typedef $(classname)::parselist parselist;",
		};

		public static readonly string [] g_syntaxTreeBaseCppSrc =
		{
			"#include \"SyntaxTreeBase.h\"",
			"",
			"int SyntaxTreeBase::g_created = 0;",
			"int SyntaxTreeBase::g_deleted = 0;",
			"int SyntaxTreeBase::g_traverse = 0;",
			"int SyntaxTreeToken::g_tokens = 0;",
			"int SyntaxTreeToken::g_counter = 0;",
			"",
			"const char* SyntaxTreeError::g_errorStrings[] =",
			"{",
			"\t\"Unknown error\",",
			"\t\"Invalid kind of constructor '%s'\",",
			"};",
			"",
			"unsigned int SyntaxTreeError::g_errorCount = sizeof g_errorStrings / sizeof g_errorStrings[0];",
			"",
			"SyntaxTreeBase::SyntaxTreeBase (unsigned int id, unsigned int kind)",
			"{",
			"\t++g_created;",
			"\tm_locked = false;",
			"\tm_usageCount = 0;",
			"\tm_id = id;",
			"\tm_kind = kind;",
			"\tm_turn = 0;",
			"\tm_parent = 0;",
			"\tm_appInfo = 0;",
			"\t",
			"}",
			"",
			"SyntaxTreeBase::~SyntaxTreeBase ()",
			"{",
			"\t++g_deleted;",
			"\tfor (synlist::iterator it = m_synlist.begin(); it != m_synlist.end(); ++it)",
			"\t{",
			"\t\tif ((*it)->decUsage() <= 0)",
			"\t\t\tdelete *it;",
			"\t}",
			"\tm_synlist.clear();",
			"\tm_parent = 0;",
			"}",
			"",
			"void SyntaxTreeBase::join (SyntaxTreeBase* node)",
			"{",
			"\tm_synlist.push_back (node);",
			"\tnode->incUsage();",
			"}",
		};

		public static readonly string [] g_syntaxTreeBaseCppHdr =
		{
			"#pragma once",
			"",
			"#include <string>",
			"#include <memory>",
			"#include <list>",
			"using namespace std;",
			"typedef unsigned int u_int;",
			"typedef unsigned short token_type;",
			"",
			"class SyntaxTreeError",
			"{",
			"public:",
			"\tSyntaxTreeError (unsigned int errorCode, const char* errorStrings[]) : m_errorCode (errorCode), m_errorStrings ((const char**) errorStrings) {}",
			"\tvirtual ~SyntaxTreeError () {}",
			"\tinline unsigned int errorCode () { return m_errorCode; }",
			"\tinline const char* errorString () { return (m_errorCode >= g_errorCount) ? 0 : g_errorStrings[m_errorCode]; }",
			"",
			"public:",
			"\tstatic const unsigned int InvalidKindError = 1;",
			"private:",
			"\tstatic const char* g_errorStrings[];",
			"\tstatic unsigned int g_errorCount;",
			"\tunsigned int m_errorCode;",
			"\tconst char** m_errorStrings;",
			"};",
			"",
			"class\tSyntaxTreeBase",
			"{",
			"public:",
			"\ttypedef shared_ptr < SyntaxTreeBase > synptr;",
			"\ttypedef list < SyntaxTreeBase* > synlist;",
			"\tSyntaxTreeBase (unsigned int id, unsigned int kind);",
			"\tSyntaxTreeBase (SyntaxTreeBase& p_syn) : SyntaxTreeBase (p_syn.id(), p_syn.kind()) { ++g_created; }",
			"\tvirtual\t~SyntaxTreeBase ();",
			"\tinline void lock () { m_locked = true; }",
			"\tinline void unlock () { m_locked = false; }",
			"\tinline bool isLocked () { return m_locked; }",
			"\tinline int incUsage () { return ++m_usageCount; }",
			"\tinline int decUsage () { return --m_usageCount; }",
			"\tinline int usageCount () { return m_usageCount; }",
			"\tinline unsigned int id () { return m_id; }",
			"\tinline unsigned int kind () { return m_kind; }",
			"\tinline void kind (unsigned int kind) { m_kind = kind; }",
			"\tinline unsigned int turn () { return m_turn; }",
			"\tinline void turn_reset () { m_turn = 0; }",
			"\tinline void turn_inc () { ++m_turn; }",
			"\tinline void* getAppInfo () { return m_appInfo; }",
			"\tinline void setAppInfo (void* appInfo) { m_appInfo = appInfo; }",
			"\tinline SyntaxTreeBase* parent () { return m_parent; }",
			"\tinline void parent (SyntaxTreeBase* parent) { m_parent = parent; }",
			"\tvoid join (SyntaxTreeBase* node);",
			"\tinline synlist& joinList () { return m_synlist; }",
			"\tvirtual bool checkInclusion (SyntaxTreeBase* element) { return element == this; }",
			"\tinline virtual SyntaxTreeBase* Clone () = 0;",
			"\tvirtual string Emit (int depth) = 0;",
			"\tvirtual string EmitProductionTree (int depth) = 0;",
			"\tvirtual void reparent (SyntaxTreeBase* parent) = 0;",
			"public:",
			"\tstatic int g_created;",
			"\tstatic int g_deleted;",
			"\tstatic int g_traverse;",
			"protected:",
			"\tbool m_locked;",
			"\tint m_usageCount;",
			"\tunsigned int m_id;",
			"\tunsigned int m_kind;",
			"\tunsigned int m_turn;",
			"\tSyntaxTreeBase* m_parent;",
			"\tsynlist m_synlist;",
			"\tvoid* m_appInfo;",
			"};",
			"",
			"class\tSyntaxTreeToken : public SyntaxTreeBase",
			"{",
			"public:",
			"\tSyntaxTreeToken (int token, int lineno, int column, char* text) : SyntaxTreeBase (0, 0), m_token (token), m_lineno (lineno), m_column (column), m_text ((text != 0) ? _strdup (text) : 0) {++g_tokens; ++g_counter; }",
			"\tSyntaxTreeToken (SyntaxTreeToken& p_token) : SyntaxTreeBase (0, 0), m_token (p_token.m_token), m_lineno (p_token.m_lineno), m_column (p_token.m_column), m_text ((p_token.m_text != 0) ? _strdup (p_token.m_text) : 0) {++g_tokens; ++g_counter; }",
			"\tvirtual\t~SyntaxTreeToken () { if (m_text != 0) free (m_text); --g_counter; }",
			"\tinline int token () { return m_token; }",
			"\tinline int lineno () { return m_lineno; }",
			"\tinline int column () { return m_column; }",
			"\tinline char* text () { return m_text; }",
			"\tinline void text (const char* text) { if (m_text != 0) free (m_text); m_text = (text != 0) ? _strdup (text) : 0; }",
			"\tinline virtual bool checkInclusion (SyntaxTreeBase* element) { return element == this; }",
			"\tinline virtual string Emit (int depth) { return (depth != 0) ? m_text : \"\"; }",
			"\tinline virtual string EmitProductionTree (int depth) { return \"\"; }",
			"\tinline virtual SyntaxTreeBase* Clone () { return (SyntaxTreeBase*) new SyntaxTreeToken (*this); }",
			"\tinline virtual void reparent (SyntaxTreeBase* parent) { this->parent (parent); }",
			"\tstatic int g_tokens;",
			"public:",
			"\tstatic int g_counter;",
			"private:",
			"\tint m_token;",
			"\tint m_lineno;",
			"\tint m_column;",
			"\tchar* m_text;",
			"};",
			"",
			"typedef SyntaxTreeBase::synptr synptr;",
			"typedef SyntaxTreeBase::synlist synlist;",
		};

		public static readonly string [] g_ScannerSkeletonHdr =
		{
			"#include \"$(RegexClassName).h\"",
			"#include <iostream>",
			"#include <fstream>",
			"#include <stack>",
			"#include <regex>",
			"using namespace std;",
			"",
			"class InputDriver",
			"{",
			"public:",
			"\tvirtual char* ReadLine () = 0;",
			"};",
			"",
			"class DefaultDriver : public InputDriver",
			"{",
			"public:",
			"\tvirtual char* ReadLine ();",
			"};",
			"",
			"class FileDriver : public InputDriver",
			"{",
			"public:",
			"\tFileDriver (ifstream* textReader);",
			"\t~FileDriver ();",
			"\tchar* ReadLine ();",
			"",
			"private:",
			"\tifstream* textReader;",
			"\tchar* buffer;",
			"\tstreamsize size;",
			"};",
			"",
			"class StringArrayDriver : public InputDriver",
			"{",
			"public:",
			"\tStringArrayDriver (int lineCount, char* lines []);",
			"\t~StringArrayDriver ();",
			"\tchar* ReadLine ();",
			"",
			"private:",
			"\tint lineCounter;",
			"\tint lineCount;",
			"\tchar** lines;",
			"};",
			"",
			"class StringDriver : public InputDriver",
			"{",
			"public:",
			"\tStringDriver (char* line);",
			"\t~StringDriver ();",
			"\tchar* ReadLine ();",
			"",
			"private:",
			"\tbool ind;",
			"\tchar* line;",
			"};",
			"",
			"$(ScannerClassDef)",
			"{",
			"private:",
			"\tstruct matchValue",
			"\t{",
			"\t\tint token;",
			"\t\tint length;",
			"\t};",
			"",
			"\tstruct lexContext",
			"\t{",
			"\t\tInputDriver* inputDriver;",
			"\t\tchar* inputString;",
			"\t\tint lineno;",
			"\t\tint column;",
			"\t};",
			"",
			"public:",
			"\tCsharpScanner (ifstream* textReader);",
			"\tCsharpScanner (int lineCount, char* lines []);",
			"\tCsharpScanner (char* line);",
			"\tint scan ();",
			"private:",
			"\tint _scan ();",
			"\tstruct matchValue match ();",
			"\tvoid pushScanner (int regexIndex);",
			"\tvoid popScanner ();",
			"\tvoid pushInput (ifstream* textReader);",
			"\tvoid pushInput (int lineCount, char* lines []);",
			"\tvoid pushInput (char* line);",
			"\tbool popInput ();",
			"public:",
			"\ttypedef int (*scannerEnterCallback) (void* appData);",
			"\ttypedef void (*scannerLeaveCallback) (void* appData, int token);",
			"\ttypedef void (*scannerPushCallback) (void* appData, int ctx);",
			"\ttypedef void (*scannerPopCallback) (void* appData, int ctx);",
			"",
			"\tpair <scannerEnterCallback, void*> scannerEnterEvent = pair <scannerEnterCallback, void*> (nullptr, nullptr);",
			"\tpair <scannerLeaveCallback, void*> scannerLeaveEvent = pair <scannerLeaveCallback, void*> (nullptr, nullptr);",
			"\tpair <scannerPushCallback, void*> scannerPushEvent = pair <scannerPushCallback, void*> (nullptr, nullptr);",
			"\tpair <scannerPopCallback, void*> scannerPopEvent = pair <scannerPopCallback, void*> (nullptr, nullptr);",
			"",
			"private:",
			"\tInputDriver* inputDriver = new DefaultDriver ();",
			"\tchar* currentLine = (char*) \"\";",
			"\tint internalLineno = 0;",
			"\tint internalColumn = 0;",
			"\tstack<int> regqueue;",
			"\tstack<lexContext> inputDrivers;",
			"\tanglrRegexScanner* lregex;",
			"\tregex anreg;",
			"\tbool anregInd = false;",
			"",
			"public:",
			"\tinline int regexIndex () {return m_regexIndex; }",
			"\tinline int scase () {return m_scase;}",
			"\tinline int lineno () {return m_lineno;}",
			"\tinline int column () {return m_column;}",
			"\tinline int token () {return m_token;}",
			"\tinline int secondary () {return m_secondary;}",
			"\tinline char* text () {return (m_text != nullptr) ? m_text : (char*) \"\";}",
			"",
			"private:",
			"\tint m_regexIndex = -1;",
			"\tint m_scase = -1;",
			"\tint m_lineno = 0;",
			"\tint m_column = 0;",
			"\tint m_token = -1;",
			"\tint m_secondary = -1;",
			"\tchar* m_text = nullptr;",
			"\tint m_textLength = 0;",
			"",
			"\t// array of regular expression scanners",
			"private:",
			"\tstatic anglrRegexScanner* regarray [];",
			"",
			"public:",
			"\t// scanner codes",
			"$(ScannerCodes)",
			"$(ScannerAnonCode)",
			"",
			"};",
			""
		};

		public static readonly string [] g_ScannerSkeletonSrc =
		{
			"",
			"#include \"$(ScannerClassRef).h\"",
			"",
			"char* DefaultDriver::ReadLine ()",
			"{",
			"\treturn (char*) 0;",
			"}",
			"",
			"FileDriver::FileDriver (ifstream* textReader)",
			"{",
			"\tthis->textReader = textReader;",
			"\tbuffer = (char*) calloc (size = 1024, 1);",
			"}",
			"",
			"FileDriver::~FileDriver ()",
			"{",
			"\tif (buffer != nullptr)",
			"\t\tfree (buffer);",
			"\tbuffer = nullptr;",
			"\tsize = 0;",
			"}",
			"",
			"char* FileDriver::ReadLine ()",
			"{",
			"\tstreamsize position = 0;",
			"\tstreamsize rdsize = size;",
			"\twhile (true)",
			"\t{",
			"\t\ttextReader->getline (buffer + position, rdsize);",
			"\t\tif (textReader->good ())",
			"\t\t\tbreak;",
			"\t\tif (textReader->fail ())",
			"\t\t{",
			"\t\t\tif (textReader->eof () || (textReader->gcount () <= 0))",
			"\t\t\t{",
			"\t\t\t\tif (*buffer == 0)",
			"\t\t\t\t{",
			"\t\t\t\t\tfree (buffer);",
			"\t\t\t\t\tbuffer = 0;",
			"\t\t\t\t\tsize = 0;",
			"\t\t\t\t}",
			"\t\t\t\tbreak;",
			"\t\t\t}",
			"\t\t}",
			"\t\tchar* tmp = buffer;",
			"\t\tposition = size;",
			"\t\trdsize = 1024;",
			"\t\tbuffer = (char*) realloc (buffer, size += 1024);",
			"\t\tfree (tmp);",
			"\t}",
			"\treturn buffer;",
			"}",
			"",
			"StringArrayDriver::StringArrayDriver (int lineCount, char* lines [])",
			"{",
			"\tthis->lineCount = lineCount;",
			"\tthis->lines = lines;",
			"\tlineCounter = 0;",
			"}",
			"",
			"StringArrayDriver::~StringArrayDriver ()",
			"{",
			"\tlineCount = 0;",
			"\tlines = nullptr;",
			"}",
			"",
			"char* StringArrayDriver::ReadLine ()",
			"{",
			"\tif (lineCounter < lineCount)",
			"\t\treturn lines [lineCounter++];",
			"\treturn nullptr;",
			"}",
			"",
			"StringDriver::StringDriver (char* line)",
			"{",
			"\tthis->line = line;",
			"\tind = false;",
			"}",
			"",
			"StringDriver::~StringDriver ()",
			"{",
			"\tline = nullptr;",
			"}",
			"",
			"char* StringDriver::ReadLine ()",
			"{",
			"\tif (ind)",
			"\t\treturn nullptr;",
			"\tind = true;",
			"\treturn line;",
			"}",
			"",
			"anglrRegexScanner* $(ScannerClassRef)::regarray [] =",
			"{",
			"$(ScannerRegexList)",
			"};",
			"",
			"$(ScannerClassRef)::$(ScannerClassRef) (ifstream* textReader)",
			"{",
			"\tpushInput (textReader);",
			"\tpushScanner (csharpScanner);",
			"}",
			"",
			"$(ScannerClassRef)::$(ScannerClassRef) (int lineCount, char* lines [])",
			"{",
			"\tpushInput (lineCount, lines);",
			"\tpushScanner (csharpScanner);",
			"}",
			"",
			"$(ScannerClassRef)::$(ScannerClassRef) (char* line)",
			"{",
			"\tpushInput (line);",
			"\tpushScanner (csharpScanner);",
			"}",
			"",
			"int $(ScannerClassRef)::scan ()",
			"{",
			"\tm_token = m_secondary = -1;",
			"\tm_token = _scan ();",
			"\tif (scannerLeaveEvent.first != nullptr)",
			"\t\t(*scannerLeaveEvent.first) (scannerLeaveEvent.second, m_token);",
			"\treturn m_token;",
			"}",
			"",
			"int $(ScannerClassRef)::_scan ()",
			"{",
			"\twhile (true)",
			"\t{",
			"\t\twhile (*currentLine == 0)",
			"\t\t{",
			"\t\t\tif ((currentLine = inputDriver->ReadLine ()) == nullptr)",
			"\t\t\t{",
			"\t\t\t\tif (popInput ())",
			"\t\t\t\t\tcontinue;",
			"\t\t\t\treturn -1;",
			"\t\t\t}",
			"\t\t\tm_lineno = ++internalLineno;",
			"\t\t\tinternalColumn = 0;",
			"\t\t}",
			"\t\tif (scannerEnterEvent.first != nullptr)",
			"\t\t{",
			"\t\t\tint token = (*scannerEnterEvent.first)(scannerEnterEvent.second);",
			"\t\t\tif (token > 0)",
			"\t\t\t\treturn token;",
			"\t\t}",
			"",
			"\t\tmatchValue result = match ();",
			"\t\tm_scase = result.token;",
			"\t\tint length = result.length;",
			"\t\tif (m_textLength <= length)",
			"\t\t{",
			"\t\t\tif (m_text != nullptr)",
			"\t\t\t\tfree (m_text);",
			"\t\t\tm_text = (char*) malloc (m_textLength = (((length + 1) >> 10) + 1) << 10);",
			"\t\t}",
			"\t\tmemcpy (m_text, currentLine, length);",
			"\t\tm_text [length] = 0;",
			"\t\tm_column = internalColumn;",
			"\t\tinternalColumn += result.length;",
			"\t\tcurrentLine += result.length;",
			"\t\tint regexIndex = m_regexIndex;",
			"$(ScannerCode)",
			"\t\treturn result.token;",
			"\t}",
			"}",
			"",
			"struct $(ScannerClassRef)::matchValue $(ScannerClassRef)::match ()",
			"{",
			"\ttry",
			"\t{",
			"\t\tif (lregex->scan (currentLine) > 0)",
			"\t\t\treturn matchValue {lregex->token (), (int) strlen (lregex->matchstr ())};",
			"\t\treturn matchValue {0, 0};",
			"\t}",
			"\tcatch (...)",
			"\t{",
			"\t\treturn matchValue {-2, 0};",
			"\t}",
			"}",
			"",
			"void $(ScannerClassRef)::pushScanner (int regexIndex)",
			"{",
			"\tif (scannerPushEvent.first != nullptr)",
			"\t\t(*scannerPushEvent.first)(scannerPushEvent.second, regexIndex);",
			"\tregqueue.push (this->m_regexIndex = regexIndex);",
			"\tthis->lregex = regarray [regexIndex];",
			"}",
			"",
			"void $(ScannerClassRef)::popScanner ()",
			"{",
			"\tregqueue.pop ();",
			"\tlregex = regarray [m_regexIndex = regqueue.top ()];",
			"\tif (scannerPopEvent.first != nullptr)",
			"\t\t(*scannerPopEvent.first) (scannerPopEvent.second, m_regexIndex);",
			"}",
			"",
			"void $(ScannerClassRef)::pushInput (ifstream* textReader)",
			"{",
			"\tinputDrivers.push (lexContext {inputDriver, currentLine, internalLineno, internalColumn});",
			"\tinputDriver = new FileDriver (textReader);",
			"\tcurrentLine = (char*) \"\";",
			"\tinternalLineno = 0;",
			"\tinternalColumn = 0;",
			"}",
			"",
			"void $(ScannerClassRef)::pushInput (int lineCount, char* lines [])",
			"{",
			"\tinputDrivers.push (lexContext {inputDriver, currentLine, internalLineno, internalColumn});",
			"\tinputDriver = new StringArrayDriver (lineCount, lines);",
			"\tcurrentLine = (char*) \"\";",
			"\tinternalLineno = 0;",
			"\tinternalColumn = 0;",
			"}",
			"",
			"void $(ScannerClassRef)::pushInput (char* line)",
			"{",
			"\tinputDrivers.push (lexContext {inputDriver, currentLine, internalLineno, internalColumn});",
			"\tinputDriver = new StringDriver (line);",
			"\tcurrentLine = (char*) \"\";",
			"\tinternalLineno = 0;",
			"\tinternalColumn = 0;",
			"}",
			"",
			"bool $(ScannerClassRef)::popInput ()",
			"{",
			"\tif (inputDrivers.size () <= 0)",
			"\t\treturn false;",
			"\tlexContext ctx = inputDrivers.top ();",
			"\tinputDriver = ctx.inputDriver;",
			"\tcurrentLine = ctx.inputString;",
			"\tinternalLineno = ctx.lineno;",
			"\tinternalColumn = ctx.column;",
			"\tinputDrivers.pop ();",
			"\treturn inputDrivers.size () > 0;",
			"}",
		};
	}
}
