// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage ("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_FinalStepEvent_Async(System.Int32)")]
[assembly: SuppressMessage ("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_FinalStepEvent_Async(System.Int32)")]
[assembly: SuppressMessage ("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_JoinEvent_Async(System.Int32,System.Int32)")]
[assembly: SuppressMessage ("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_JoinEvent_Async(System.Int32,System.Int32)")]
[assembly: SuppressMessage ("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_LoopStepEvent_Async(System.Int32,System.Int32)")]
[assembly: SuppressMessage ("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_LoopStepEvent_Async(System.Int32,System.Int32)")]
[assembly: SuppressMessage ("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_ReduceStepEvent_Async(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,Anglr.Parser.SyntaxTree.SyntaxTreeBase,System.Boolean)")]
[assembly: SuppressMessage ("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_ReduceStepEvent_Async(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,Anglr.Parser.SyntaxTree.SyntaxTreeBase,System.Boolean)")]
[assembly: SuppressMessage ("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_ShiftStepEvent_Async(System.Int32,System.Int32,System.Int32,System.String,System.Boolean)")]
[assembly: SuppressMessage ("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_ShiftStepEvent_Async(System.Int32,System.Int32,System.Int32,System.String,System.Boolean)")]
[assembly: SuppressMessage ("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_SplitStepEvent_Async(System.Int32,System.Int32,System.Boolean)")]
[assembly: SuppressMessage ("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_SplitStepEvent_Async(System.Int32,System.Int32,System.Boolean)")]
[assembly: SuppressMessage ("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_StartParserEvent_Async(System.Int32)")]
[assembly: SuppressMessage ("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_StartParserEvent_Async(System.Int32)")]
[assembly: SuppressMessage ("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_StopParserEvent_Async")]
[assembly: SuppressMessage ("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_StopParserEvent_Async")]
[assembly: SuppressMessage ("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_SyntaxErrorEvent_Async(System.Int32,System.Int32)")]
[assembly: SuppressMessage ("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:AnglrDebuggerBridge.AnglrDebuggerClientBridge.ParserInterface_SyntaxErrorEvent_Async(System.Int32,System.Int32)")]
